<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$err='';
$types=['ENSAIO SEMANAL','ENSAIO POR ALA','ENSAIO GERAL','ENSAIO PRA CAMPEONATO','REUNIÃO','CAMPEONATO','APRESENTAÇÃO','EVENTO ESPECIAL','OUTRO'];
$areas=array_merge(['GERAL / TODA A BANDA','COORDENAÇÃO'],enrollment_instruments());
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{csrf_check();$action=$_POST['action']??'save';
  if($action==='delete'){$pdo->prepare("DELETE FROM agenda WHERE id=?")->execute([(int)$_POST['id']]);go('agenda.php','Evento removido.');}
  $id=(int)($_POST['id']??0);$title=trim((string)($_POST['title']??''));$date=trim((string)($_POST['event_date']??''));$time=trim((string)($_POST['event_time']??''));$end=trim((string)($_POST['end_time']??''));$type=trim((string)($_POST['event_type']??'OUTRO'));$location=trim((string)($_POST['location']??''));$area=trim((string)($_POST['area']??''));$desc=trim((string)($_POST['description']??''));$published=isset($_POST['published'])?1:0;$featured=isset($_POST['featured'])?1:0;
  if(mb_strlen($title)<3)throw new RuntimeException('Informe o nome do compromisso.');if(!preg_match('/^\\d{4}-\\d{2}-\\d{2}$/',$date))throw new RuntimeException('Informe a data do compromisso.');if(!in_array($type,$types,true))$type='OUTRO';
  if($featured)$pdo->exec("UPDATE agenda SET featured=0");
  if($id>0){$pdo->prepare("UPDATE agenda SET title=?,event_date=?,event_time=?,end_time=?,event_type=?,location=?,area=?,description=?,published=?,featured=? WHERE id=?")->execute([$title,$date,$time,$end,$type,$location,$area,$desc,$published,$featured,$id]);go('agenda.php','Compromisso atualizado e arte recalculada automaticamente.');}
  $pdo->prepare("INSERT INTO agenda(title,event_date,event_time,end_time,event_type,location,area,description,published,featured,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)")->execute([$title,$date,$time,$end,$type,$location,$area,$desc,$published,$featured,now_iso()]);go('agenda.php','Compromisso publicado. A arte apareceu automaticamente na Agenda do site.');
 }catch(Throwable $e){$err=$e->getMessage();}
}
$editId=(int)($_GET['edit']??0);$edit=null;if($editId){$st=$pdo->prepare("SELECT * FROM agenda WHERE id=?");$st->execute([$editId]);$edit=$st->fetch()?:null;}
$rows=$pdo->query("SELECT * FROM agenda ORDER BY event_date DESC, CASE WHEN event_time='' THEN '23:59' ELSE event_time END DESC, id DESC")->fetchAll();
admin_header('Agenda Interativa');$msg=flash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="panel agenda-admin-intro"><div class="panel-heading-flex"><div><span>AGENDA INTERATIVA BAMAB</span><h2>Publique o compromisso e a Agenda Interativa faz o restante</h2><p>O sistema monta automaticamente a arte pública com brasão, data, horário, local, tipo e ala. O site também gera relógio em tempo real, contagem regressiva, calendário interativo e arquivo para adicionar o compromisso ao calendário do celular.</p></div><a class="small-button" href="../agenda.php" target="_blank" rel="noopener noreferrer">VER AGENDA NO SITE</a></div></section>
<form class="panel form-stack agenda-admin-form" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$editId?>"><input type="hidden" name="action" value="save"><h2><?=$edit?'Editar compromisso':'Novo compromisso'?></h2><div class="grid2"><label>Nome do compromisso<input name="title" value="<?=e($edit['title']??'')?>" required placeholder="Ex.: Ensaio Geral"></label><label>Tipo<select name="event_type" required><?php foreach($types as $tp):?><option value="<?=e($tp)?>" <?=($edit['event_type']??'')===$tp?'selected':''?>><?=e($tp)?></option><?php endforeach;?></select></label><label>Data<input type="date" name="event_date" value="<?=e($edit['event_date']??date('Y-m-d'))?>" required></label><label>Horário inicial<input type="time" name="event_time" value="<?=e($edit['event_time']??'')?>"></label><label>Horário final <small>(usado também na agenda/calendário)</small><input type="time" name="end_time" value="<?=e($edit['end_time']??'')?>"></label><label>Local<input name="location" value="<?=e($edit['location']??'')?>" placeholder="Ex.: Sede da BAMAB"></label><label>Ala / responsável<select name="area"><option value="">NÃO INFORMADO</option><?php foreach($areas as $area):?><option value="<?=e($area)?>" <?=($edit['area']??'')===$area?'selected':''?>><?=e($area)?></option><?php endforeach;?></select></label><div class="agenda-admin-flags"><label class="check"><input type="checkbox" name="published" <?=!$edit||(int)$edit['published']===1?'checked':''?>> Publicar no site</label><label class="check"><input type="checkbox" name="featured" <?=($edit['featured']??0)?'checked':''?>> Marcar como destaque na Agenda Interativa</label></div></div><label>Descrição / aviso<textarea name="description" rows="4" placeholder="Informações importantes para músicos e responsáveis."><?=e($edit['description']??'')?></textarea></label><div class="agenda-form-actions"><button class="primary"><?=$edit?'SALVAR ALTERAÇÕES':'PUBLICAR NA AGENDA'?></button><?php if($edit):?><a class="small-button" href="agenda.php">CANCELAR EDIÇÃO</a><?php endif;?></div></form>
<section class="panel"><div class="panel-heading-flex"><div><h2>Compromissos cadastrados</h2><p>Editar um evento atualiza imediatamente a arte exibida na Agenda pública.</p></div></div><div class="agenda-admin-grid"><?php foreach($rows as $r):$d=new DateTime($r['event_date']);?><article><div class="agenda-admin-date"><strong><?=e($d->format('d'))?></strong><span><?=e($d->format('m/Y'))?></span></div><div class="agenda-admin-info"><small><?=e($r['event_type']?:'OUTRO')?> <?=($r['featured']??0)?'· DESTAQUE':''?></small><h3><?=e($r['title'])?></h3><p><?=e($r['event_time']?:'Horário a definir')?><?= $r['end_time']?' às '.e($r['end_time']):''?> · <?=e($r['location']?:'Local a definir')?></p><?php if($r['area']):?><b><?=e($r['area'])?></b><?php endif;?><span class="<?=$r['published']?'card-active':'card-inactive'?>"><?=$r['published']?'PUBLICADO':'OCULTO'?></span></div><div class="agenda-admin-actions"><a class="small-button" href="?edit=<?=$r['id']?>">EDITAR</a><a class="small-button" href="../agenda.php#evento-<?=$r['id']?>" target="_blank" rel="noopener noreferrer">VER ARTE</a><form method="post" onsubmit="return confirm('Excluir este compromisso da agenda?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger">EXCLUIR</button></form></div></article><?php endforeach;?><?php if(!$rows):?><div class="empty-cell">Nenhum compromisso cadastrado.</div><?php endif;?></div></section>
<?php admin_footer();?>
