<?php
require __DIR__.'/../config.php';
require __DIR__.'/../report_helpers.php';
$u=require_admin();$pdo=db();$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT * FROM enrollments WHERE id=? AND deleted_at IS NULL");$st->execute([$id]);$r=$st->fetch();
if(!$r){http_response_code(404);exit('Matrícula não encontrada.');}
if((int)$r['currently_studying']!==1) exit('Esta matrícula não está marcada como estudante ativo.');
$minor=(int)$r['is_minor']===1;$signer=$minor?$r['guardian_name']:$r['student_name'];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Declaração de Compromisso e Participação</title><link rel="stylesheet" href="../assets/report_a4.css"><?=bamab_report_style_block('../')?></head><body><div class="a4-toolbar no-print"><a href="matricula_ver.php?id=<?=$id?>">← VOLTAR</a><button onclick="window.print()">IMPRIMIR / PDF A4</button></div><main class="a4-document"><header class="a4-header"><img src="<?=e(bamab_report_logo_web('../'))?>" alt="Brasão"><div class="a4-location"><?=e(report_location_line())?></div></header><section class="a4-title"><h1>DECLARAÇÃO DE COMPROMISSO E PARTICIPAÇÃO CULTURAL</h1><p>Documento vinculado à matrícula <?=e($r['registration_number']?:$r['protocol'])?></p></section>
<div class="declaration-data"><div><strong>Participante:</strong> <?=e($r['student_name'])?></div><div><strong>Instrumento / ala:</strong> <?=e($r['instrument'])?></div><div><strong>Rede de ensino:</strong> <?=e(school_network_label($r['school_network']))?></div><div><strong>Instituição de ensino:</strong> <?=e($r['school_name'])?></div></div>
<div class="a4-text"><p>Declaramos, para os devidos fins, que <strong><?=e($r['student_name'])?></strong> encontra-se regularmente cadastrado(a) e participa das atividades culturais e musicais da Banda Amaral Brasil — BAMAB, incluindo ensaios, formação musical, apresentações e demais ações institucionais programadas.</p><p>O(a) participante e, quando menor de idade, seu responsável legal, assumem o compromisso de conciliar a participação nas atividades da BAMAB com as obrigações escolares, preservando o vínculo, a frequência e as responsabilidades perante a instituição de ensino.</p><p>A presente declaração é emitida para fins de comprovação de vínculo e participação cultural, podendo ser apresentada à instituição de ensino para ciência da atividade extracurricular desenvolvida.</p></div>
<div class="a4-legal"><strong>FUNDAMENTAÇÃO LEGAL:</strong> a Constituição Federal reconhece o lazer como direito social em seu art. 6º e assegura, no art. 215, o pleno exercício dos direitos culturais e o acesso às fontes da cultura. Para crianças e adolescentes, a Lei nº 8.069/1990 — Estatuto da Criança e do Adolescente — inclui educação, esporte, lazer e cultura entre os direitos assegurados com prioridade, além de estimular a participação em atividades culturais.</div>
<div class="a4-warning"><strong>IMPORTANTE:</strong> esta declaração comprova vínculo e participação cultural. Ela não substitui regras internas da escola, não autoriza automaticamente ausências em aulas e não produz, por si só, abono de faltas. A eventual aceitação depende da análise da instituição de ensino.</div>
<p class="declaration-date"><?=e(report_location_line())?>, <?=date('d/m/Y')?>.</p><section class="a4-signatures"><div class="a4-signature"><div class="line"></div><strong>COORDENADOR GERAL</strong></div><div class="a4-signature"><div class="line"></div><strong>INSTRUTOR RESPONSÁVEL</strong></div><div class="a4-signature"><div class="line"></div><strong>SECRETÁRIO(A)</strong></div></section><div class="a4-participant-signature"><div class="line"></div><strong><?= $minor?'RESPONSÁVEL LEGAL':'PARTICIPANTE'?> — <?=e($signer)?></strong></div><footer class="a4-footer">Declaração gerada em <?=date('d/m/Y H:i')?>.</footer></main></body></html>
