<?php
require __DIR__.'/../config.php';
require __DIR__.'/../report_helpers.php';
$u=require_admin();$pdo=db();$id=(int)($_GET['id']??0);$st=$pdo->prepare("SELECT * FROM enrollments WHERE id=? AND deleted_at IS NULL");$st->execute([$id]);$r=$st->fetch();if(!$r){http_response_code(404);exit('Matrícula não encontrada.');}if((int)$r['works_currently']!==1||(int)$r['needs_work_declaration']!==1)exit('Esta matrícula não possui solicitação de declaração para trabalho.');
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Declaração de Participação Cultural</title><link rel="stylesheet" href="../assets/report_a4.css"><?=bamab_report_style_block('../')?></head><body><div class="a4-toolbar no-print"><a href="matricula_ver.php?id=<?=$id?>">← VOLTAR</a><button onclick="window.print()">IMPRIMIR / PDF A4</button></div><main class="a4-document"><header class="a4-header"><img src="<?=e(bamab_report_logo_web('../'))?>" alt="Brasão"><div class="a4-location"><?=e(report_location_line())?></div></header><section class="a4-title"><h1>DECLARAÇÃO DE PARTICIPAÇÃO CULTURAL</h1><p>Para fins de apresentação ao trabalho</p></section>
<div class="declaration-data"><div><strong>Participante:</strong> <?=e($r['student_name'])?></div><div><strong>Matrícula BAMAB:</strong> <?=e($r['registration_number']?:$r['protocol'])?></div><div><strong>Instrumento / ala:</strong> <?=e($r['instrument'])?></div><div><strong>Empresa / empregador informado:</strong> <?=e($r['employer_name'])?></div></div>
<div class="a4-text"><p>Declaramos, para os devidos fins, que <strong><?=e($r['student_name'])?></strong> encontra-se regularmente cadastrado(a) e participa das atividades culturais e musicais da Banda Amaral Brasil — BAMAB, incluindo ensaios, formação musical, apresentações, desfiles, campeonatos e demais atividades institucionais previamente programadas.</p><p>O presente documento é emitido a pedido do participante para comprovar seu vínculo e sua participação em atividade cultural, podendo ser apresentado ao empregador para ciência e eventual análise de compatibilização de horários.</p></div>
<div class="a4-legal"><strong>REFERÊNCIA CONSTITUCIONAL:</strong> o art. 6º da Constituição Federal reconhece o lazer como direito social, e o art. 215 assegura a todos o pleno exercício dos direitos culturais e o acesso às fontes da cultura nacional.</div>
<div class="a4-warning"><strong>IMPORTANTE:</strong> esta declaração não cria, por si só, direito a dispensa do trabalho, alteração de jornada ou abono de faltas. Qualquer liberação ou ajuste de horário depende da decisão do empregador e das normas trabalhistas aplicáveis.</div>
<p class="declaration-date"><?=e(report_location_line())?>, <?=date('d/m/Y')?>.</p>
<section class="a4-signatures"><div class="a4-signature"><div class="line"></div><strong>COORDENADOR GERAL</strong></div><div class="a4-signature"><div class="line"></div><strong>INSTRUTOR RESPONSÁVEL</strong></div><div class="a4-signature"><div class="line"></div><strong>SECRETÁRIO(A)</strong></div></section><div class="a4-participant-signature"><div class="line"></div><strong>PARTICIPANTE — <?=e($r['student_name'])?></strong></div><footer class="a4-footer">Declaração gerada em <?=date('d/m/Y H:i')?>.</footer></main></body></html>
