<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();try{$a=$_POST['action']??'';
 if($a==='save_terms'){foreach(['team_registration_title','team_registration_intro','team_terms_version','term_name_respect','team_term_commitment','team_term_image','team_term_privacy'] as $k)set_setting($k,trim((string)($_POST[$k]??'')));go('equipe.php','Textos da ficha atualizados.');}
 if($a==='add_role'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$name=mb_strtoupper(trim((string)$_POST['name']));$cat=mb_strtoupper(trim((string)$_POST['category']));if($name==='')throw new RuntimeException('Informe a função.');$pdo->prepare("INSERT INTO team_roles(name,category,active,sort_order,created_at) VALUES(?,?,1,?,?)")->execute([$name,$cat?:'EQUIPE',(int)($_POST['sort_order']??100),now_iso()]);go('equipe.php','Função adicionada.');}
 if($a==='edit_role'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$id=(int)$_POST['role_id'];$name=mb_strtoupper(trim((string)$_POST['name']));$cat=mb_strtoupper(trim((string)$_POST['category']));$pdo->prepare("UPDATE team_roles SET name=?,category=?,active=?,sort_order=? WHERE id=?")->execute([$name,$cat?:'EQUIPE',isset($_POST['active'])?1:0,(int)$_POST['sort_order'],$id]);go('equipe.php','Função atualizada.');}
 if($a==='delete_role'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$id=(int)$_POST['role_id'];$st=$pdo->prepare("SELECT COUNT(*) FROM team_members WHERE role_id=?");$st->execute([$id]);if((int)$st->fetchColumn()>0)throw new RuntimeException('A função já está vinculada a inscrições. Desative-a em vez de excluir.');$pdo->prepare("DELETE FROM team_roles WHERE id=?")->execute([$id]);go('equipe.php','Função excluída.');}
}catch(Throwable $e){$err=$e->getMessage();}}
$q=trim((string)($_GET['q']??''));$status=trim((string)($_GET['status']??''));$roleId=(int)($_GET['role_id']??0);$where=['tm.deleted_at IS NULL'];$params=[];
if($q!==''){$where[]='(tm.full_name LIKE ? OR tm.preferred_name LIKE ? OR tm.application_number LIKE ?)';$lk='%'.$q.'%';array_push($params,$lk,$lk,$lk);}
if($status!==''&&array_key_exists($status,team_statuses())){$where[]='tm.status=?';$params[]=$status;}
if($roleId>0){$where[]='tm.role_id=?';$params[]=$roleId;}
$st=$pdo->prepare("SELECT tm.*,tr.name role_name FROM team_members tm LEFT JOIN team_roles tr ON tr.id=tm.role_id WHERE ".implode(' AND ',$where)." ORDER BY tm.full_name COLLATE NOCASE");$st->execute($params);$rows=$st->fetchAll();$roles=team_roles(false);
admin_header('Equipe BAMAB — Inscrições e Crachás');$msg=flash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>

<section class="panel internal-team-control"><div class="panel-heading-flex"><div><span>CADASTRO RESTRITO</span><h2>Equipe interna da BAMAB</h2><p>Coordenação, Coreógrafo, Mó, Baliza, Mídia, Secretário, Produção, Coordenador, Coordenador Geral e demais cargos internos são cadastrados somente pelo Admin Geral.</p></div><?php if(is_general_admin($u)):?><a class="admin-action-link internal-new-member" href="equipe_novo.php">+ NOVO MEMBRO INTERNO</a><?php endif;?></div></section>
<section class="panel"><h2>Funções / cargos editáveis</h2><p>Você pode renomear, criar, ordenar e desativar qualquer função interna. As opções aparecem automaticamente no cadastro interno do Admin Geral e nos crachás.</p>
<form method="post" class="role-add-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_role"><label>Nova função<input name="name" required placeholder="Ex.: APOIO TÉCNICO"></label><label>Categoria<input name="category" placeholder="Ex.: PRODUÇÃO"></label><label>Ordem<input type="number" name="sort_order" value="100"></label><button class="primary">ADICIONAR</button></form>
<div class="role-admin-grid"><?php foreach($roles as $role):?><form method="post" class="role-edit-card"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="edit_role"><input type="hidden" name="role_id" value="<?=$role['id']?>"><label>Função<input name="name" value="<?=e($role['name'])?>"></label><label>Categoria<input name="category" value="<?=e($role['category'])?>"></label><label>Ordem<input type="number" name="sort_order" value="<?=$role['sort_order']?>"></label><label class="check"><input type="checkbox" name="active" <?=$role['active']?'checked':''?>> Ativa</label><button class="small-button">SALVAR</button></form><?php endforeach;?></div></section>

<section class="panel"><div class="panel-heading-flex"><div><h2>Cadastros internos da equipe</h2><p><?=count($rows)?> registro(s) no filtro atual.</p></div></div>
<form method="get" class="filter-row"><label>Pesquisar<input name="q" value="<?=e($q)?>" placeholder="Nome, nome social ou número"></label><label>Status<select name="status"><option value="">Todos</option><?php foreach(team_statuses() as $k=>$v):?><option value="<?=e($k)?>" <?=$status===$k?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label><label>Função<select name="role_id"><option value="0">Todas</option><?php foreach($roles as $rr):?><option value="<?=$rr['id']?>" <?=$roleId===(int)$rr['id']?'selected':''?>><?=e($rr['name'])?></option><?php endforeach;?></select></label><button class="primary">FILTRAR</button></form>
<div class="table-wrap"><table class="admin-table"><thead><tr><th>Nº</th><th>Foto</th><th>Nome</th><th>Como chamar</th><th>Função</th><th>Status</th><th>Crachá</th><th></th></tr></thead><tbody><?php foreach($rows as $rr):?><tr><td><strong><?=e($rr['application_number'])?></strong></td><td><?php if($rr['photo_path']):?><img class="admin-thumb-3x4" src="../<?=e($rr['photo_path'])?>" alt=""><?php endif;?></td><td><?=e($rr['full_name'])?></td><td><?=e($rr['preferred_name']?:'—')?></td><td><?=e($rr['role_name']?:'—')?></td><td><span class="status-pill"><?=e(team_status_label($rr['status']))?></span></td><td><span class="<?=$rr['badge_status']==='ATIVO'?'card-active':'card-inactive'?>"><?=e($rr['badge_status'])?></span></td><td><a class="small-button" href="equipe_ver.php?id=<?=$rr['id']?>">ABRIR</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8" class="empty-cell">Nenhuma inscrição.</td></tr><?php endif;?></tbody></table></div></section>

<section class="panel"><h2>Textos da ficha interna da equipe</h2><form method="post" class="form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_terms"><div class="grid2"><label>Título<input name="team_registration_title" value="<?=e(setting('team_registration_title'))?>"></label><label>Versão dos termos<input name="team_terms_version" value="<?=e(setting('team_terms_version'))?>"></label></div><label>Apresentação<textarea name="team_registration_intro"><?=e(setting('team_registration_intro'))?></textarea></label><label>Regra de respeito ao nome/apelido<textarea name="term_name_respect" rows="5"><?=e(setting('term_name_respect'))?></textarea></label><label>Compromisso da equipe<textarea name="team_term_commitment" rows="5"><?=e(setting('team_term_commitment'))?></textarea></label><label>Imagem e voz<textarea name="team_term_image" rows="5"><?=e(setting('team_term_image'))?></textarea></label><label>Privacidade<textarea name="team_term_privacy" rows="5"><?=e(setting('team_term_privacy'))?></textarea></label><button class="primary">SALVAR TEXTOS</button></form></section>
<?php admin_footer();?>
