<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$id=(int)($_GET['id']??$_POST['id']??0);$r=team_member($id);if(!$r){http_response_code(404);exit('Inscrição não encontrada.');}$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();try{$a=$_POST['action']??'save';
 if($a==='save'){$status=$_POST['status']??'PENDENTE';if(!array_key_exists($status,team_statuses()))$status='PENDENTE';$roleId=(int)($_POST['role_id']??$r['role_id']);$role=team_role($roleId);if(!$role)throw new RuntimeException('Função inválida.');$preferred=trim((string)($_POST['preferred_name']??''));$notes=trim((string)($_POST['admin_notes']??''));$approved=$status==='APROVADO'?($r['approved_at']?:now_iso()):$r['approved_at'];$pdo->prepare("UPDATE team_members SET status=?,role_id=?,preferred_name=?,admin_notes=?,approved_at=?,updated_at=? WHERE id=?")->execute([$status,$roleId,$preferred,$notes,$approved,now_iso(),$id]);
 if($status==='APROVADO'){activate_team_documents($id);go('equipe_ver.php?id='.$id,'Membro APROVADO. Carteirinha e crachá foram ativados automaticamente.');}
 if(in_array($status,['INATIVO','CANCELADO','RECUSADO'],true))deactivate_team_documents($id);
 go('equipe_ver.php?id='.$id,'Cadastro atualizado.');}
 if($a==='photo'){$new=upload_file($_FILES['photo'],'image');$old=$r['photo_path'];$pdo->prepare("UPDATE team_members SET photo_path=?,updated_at=? WHERE id=?")->execute([$new,now_iso(),$id]);delete_local_media((string)$old);go('equipe_ver.php?id='.$id,'Foto atualizada.');}
 if($a==='badge'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$rr=team_member($id);if($rr['status']!=='APROVADO')throw new RuntimeException('A inscrição precisa estar APROVADA.');if(!$rr['photo_path'])throw new RuntimeException('Cadastre a foto 3x4.');$valid=$_POST['valid_until']??'';if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$valid))$valid=team_badge_valid_until($rr['approved_at']?:$rr['created_at']);$pdo->prepare("UPDATE team_members SET badge_status='ATIVO',badge_issued_at=?,badge_valid_until=? WHERE id=?")->execute([now_iso(),$valid,$id]);go('equipe_ver.php?id='.$id,'Crachá ativado.');}
 if($a==='deactivate_badge'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$pdo->prepare("UPDATE team_members SET badge_status='INATIVO' WHERE id=?")->execute([$id]);go('equipe_ver.php?id='.$id,'Crachá desativado.');}
 if($a==='delete'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$pdo->prepare("UPDATE team_members SET badge_status='INATIVO',status='CANCELADO',deleted_at=?,updated_at=? WHERE id=?")->execute([now_iso(),now_iso(),$id]);go('equipe.php','Inscrição da equipe excluída e crachá desativado.');}
}catch(Throwable $e){$err=$e->getMessage();}}
$r=team_member($id);$roles=team_roles(false);admin_header('Equipe — '.$r['application_number']);$msg=flash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<div class="detail-toolbar"><a class="small-button" href="equipe.php">← VOLTAR</a><a class="small-button" target="_blank" rel="noopener noreferrer" href="ficha_equipe.php?id=<?=$id?>">IMPRIMIR FICHA A4</a><?php if($r['badge_status']==='ATIVO'):?><a class="small-button card-print-btn" target="_blank" rel="noopener noreferrer" href="carteirinha_equipe.php?id=<?=$id?>">CARTEIRINHA DA EQUIPE</a><a class="small-button card-print-btn" target="_blank" rel="noopener noreferrer" href="cracha_equipe.php?id=<?=$id?>">CRACHÁ DA EQUIPE</a><?php endif;?><a class="small-button" href="reconhecimentos.php?kind=EQUIPE&q=<?=urlencode($r['application_number'])?>&year=<?=date('Y')?>">CERTIFICADO / DIPLOMA</a></div>
<section class="panel enrollment-admin-detail"><div class="detail-header"><div><span>NÚMERO DA EQUIPE</span><h2><?=e($r['application_number'])?></h2><p>Inscrição em <?=e(date('d/m/Y H:i',strtotime($r['created_at'])))?></p></div><span class="status-pill"><?=e(team_status_label($r['status']))?></span></div>
<div class="student-photo-detail"><?php if($r['photo_path']):?><img src="../<?=e($r['photo_path'])?>" alt=""><?php else:?><div>SEM FOTO</div><?php endif;?><form method="post" enctype="multipart/form-data" class="photo-update-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="photo"><label>Atualizar foto 3x4<input type="file" name="photo" accept="image/*" required></label><button class="small-button">SALVAR FOTO</button></form></div>
<div class="detail-grid"><div><small>Nome completo</small><strong><?=e($r['full_name'])?></strong></div><div><small>Nome social / apelido autorizado</small><strong><?=e($r['preferred_name']?:'Somente o nome da pessoa')?></strong></div><div><small>Função</small><strong><?=e($r['role_name'])?></strong></div><div><small>Nascimento</small><strong><?=e(date('d/m/Y',strtotime($r['birth_date'])))?></strong></div><div><small>Telefone</small><strong><?=e($r['phone'])?></strong></div><div><small>E-mail</small><strong><?=e($r['email']?:'—')?></strong></div><div class="span2"><small>Experiência / habilidades</small><strong><?=e($r['experience']?:'—')?></strong></div></div></section>

<section class="panel name-respect-admin"><h2>Nome de uso autorizado</h2><p><?=e(setting('term_name_respect'))?></p><strong>NO SISTEMA: <?=e(display_person_name($r['full_name'],$r['preferred_name']))?></strong></section>

<section class="panel"><h2>Análise e função</h2><form method="post" class="form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="save"><div class="grid2"><label>Status<select name="status"><?php foreach(team_statuses() as $k=>$v):?><option value="<?=e($k)?>" <?=$r['status']===$k?'selected':''?>><?=e($v)?></option><?php endforeach;?></select></label><label>Função<select name="role_id"><?php foreach($roles as $role):?><option value="<?=$role['id']?>" ${(int)$r['role_id']===(int)$role['id']?'selected':''?>><?=e($role['name'])?></option><?php endforeach;?></select></label></div><label>Nome social/apelido autorizado<input name="preferred_name" value="<?=e($r['preferred_name'])?>"></label><label>Observações internas<textarea name="admin_notes" rows="5"><?=e($r['admin_notes'])?></textarea></label><button class="primary">SALVAR</button></form></section>

<section class="panel card-admin-panel"><div class="panel-heading-flex"><div><h2>Crachá da equipe</h2><p>QR integrado ao sistema de presença.</p></div><span class="<?=$r['badge_status']==='ATIVO'?'card-active':'card-inactive'?>"><?=e($r['badge_status'])?></span></div>
<?php if(is_general_admin($u)):?><div class="card-actions-admin"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="badge"><label>Validade<input type="date" name="valid_until" value="<?=e($r['badge_valid_until']?:team_badge_valid_until($r['approved_at']?:$r['created_at']))?>"></label><button class="primary">EMITIR / ATIVAR CRACHÁ</button></form><?php if($r['badge_status']==='ATIVO'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="deactivate_badge"><button class="danger">DESATIVAR CRACHÁ</button></form><a target="_blank" rel="noopener noreferrer" class="small-button card-print-btn" href="cracha_equipe.php?id=<?=$id?>">IMPRIMIR CRACHÁ</a><?php endif;?></div><?php endif;?></section>

<section class="panel recognition-person-panel"><div class="panel-heading-flex"><div><span>RECONHECIMENTO ANUAL</span><h2>Certificado ou Diploma da Equipe</h2><p>O Admin pode emitir Certificado, Diploma ou ambos. Estes documentos não exigem foto 3x4.</p></div><a class="small-button" href="reconhecimentos.php?kind=EQUIPE&q=<?=urlencode($r['application_number'])?>&year=<?=date('Y')?>">ABRIR EMISSÃO</a></div></section>

<details class="panel terms-snapshots"><summary>Ver termos registrados</summary><article><h3>Respeito ao nome/apelido</h3><p><?=nl2br(e($r['term_name_respect_snapshot']))?></p></article><article><h3>Compromisso</h3><p><?=nl2br(e($r['term_commitment_snapshot']))?></p></article><article><h3>Imagem</h3><p><?=nl2br(e($r['term_image_snapshot']))?></p></article><article><h3>Privacidade</h3><p><?=nl2br(e($r['term_privacy_snapshot']))?></p></article></details>
<section class="panel danger-zone"><h2>Excluir inscrição da equipe</h2><p>Desativa o crachá e remove o cadastro das listas normais.</p><form method="post" onsubmit="return confirm('Confirma a exclusão?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="delete"><button class="danger">EXCLUIR E DESATIVAR CRACHÁ</button></form></section>
<?php admin_footer();?>
