<?php
require __DIR__.'/../config.php';
require __DIR__.'/../report_helpers.php';
$u=require_admin();$pdo=db();$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT e.*,p.name period_name,p.start_date period_start,p.end_date period_end FROM enrollments e LEFT JOIN enrollment_periods p ON p.id=e.period_id WHERE e.id=? AND e.deleted_at IS NULL");
$st->execute([$id]);$r=$st->fetch();
if(!$r){http_response_code(404);exit('Matrícula não encontrada.');}
$age=birth_age((string)$r['birth_date']);
function ficha_date(string $d): string {$d=trim($d);if($d==='')return '—';$ts=strtotime($d);return $ts===false?'—':date('d/m/Y',$ts);}$minor=(int)$r['is_minor']===1;
$signer=$minor?(string)$r['guardian_name']:(string)$r['student_name'];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ficha de Matrícula — <?=e($r['registration_number']?:$r['protocol'])?></title><link rel="stylesheet" href="../assets/report_a4.css"><?=bamab_report_style_block('../')?><style>
.ficha-hero{display:grid;grid-template-columns:31mm 1fr;gap:5mm;align-items:center;margin:4mm 0 5mm}.ficha-photo{width:29mm;height:38mm;object-fit:cover;border:1px solid #777;background:#fff}.ficha-photo-fallback{width:29mm;height:38mm;border:1px solid #777;display:grid;place-items:center;font-size:8pt;color:#666;background:#fff}.ficha-number{border:1px solid #777;padding:3mm;background:#fffdf8}.ficha-number small,.ficha-number strong,.ficha-number span{display:block}.ficha-number small{font-size:7.5pt;text-transform:uppercase;color:#555}.ficha-number strong{font-size:15pt;margin:1mm 0;color:var(--report-primary)}.ficha-number span{font-size:8.5pt}.ficha-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:2mm}.ficha-item{border:1px solid #999;padding:2.3mm;background:#ffffffea;min-height:12mm}.ficha-item.span2{grid-column:1/-1}.ficha-item small,.ficha-item strong{display:block}.ficha-item small{font-size:7.4pt;text-transform:uppercase;color:#555;font-weight:700}.ficha-item strong{font-size:9.4pt;margin-top:1mm;overflow-wrap:anywhere}.ficha-terms{font-size:8.5pt;line-height:1.45}.ficha-terms p{margin:2mm 0}.ficha-status{display:inline-block;padding:1.5mm 3mm;border:1px solid #555;font-size:8pt;font-weight:900}.ficha-guardian-photo{width:22mm;height:29mm;object-fit:cover;border:1px solid #888;float:right;margin-left:4mm}.ficha-signature-main{width:56%;margin:16mm auto 0;text-align:center;font-size:8.5pt}.ficha-signature-main .line{border-top:1px solid #111;margin-bottom:2mm}@media print{.ficha-hero,.ficha-grid,.ficha-item,.a4-section{break-inside:avoid}.ficha-terms{break-inside:auto}}
</style></head><body><div class="a4-toolbar no-print"><a href="matricula_ver.php?id=<?=$id?>">← VOLTAR</a><button onclick="window.print()">IMPRIMIR / SALVAR PDF A4</button></div>
<main class="a4-document"><header class="a4-header"><img src="<?=e(bamab_report_logo_web('../'))?>" alt="Brasão"><div class="a4-location"><?=e(report_location_line())?></div></header><section class="a4-title"><h1>FICHA DE MATRÍCULA</h1><p>BANDA AMARAL BRASIL — BAMAB</p></section>
<section class="ficha-hero"><?php if(trim((string)$r['photo_path'])!==''):?><img class="ficha-photo" src="../<?=e($r['photo_path'])?>" alt="Foto 3x4" onerror="this.style.display='none'"> <?php else:?><div class="ficha-photo-fallback">SEM FOTO</div><?php endif;?><div class="ficha-number"><small>Número da matrícula</small><strong><?=e($r['registration_number']?:$r['protocol'])?></strong><span>Protocolo: <?=e($r['protocol'])?></span><span>Período: <?=e($r['period_name']?:'—')?></span><span>Inscrição recebida em <?=e(date('d/m/Y H:i',strtotime($r['created_at'])))?></span><span class="ficha-status"><?=e(enrollment_status_label($r['status']))?></span></div></section>
<section class="a4-section"><h2>Dados do participante</h2><div class="ficha-grid"><div class="ficha-item"><small>Nome completo</small><strong><?=e($r['student_name'])?></strong></div><div class="ficha-item"><small>Nome social / apelido autorizado</small><strong><?=e($r['preferred_name']?:'—')?></strong></div><div class="ficha-item"><small>Data de nascimento / idade</small><strong><?=e(ficha_date((string)$r['birth_date']))?><?=$age>=0?' — '.$age.' anos':''?></strong></div><div class="ficha-item"><small>CPF</small><strong><?=e($r['student_cpf']?:'—')?></strong></div><div class="ficha-item"><small>Telefone</small><strong><?=e($r['student_phone']?:'—')?></strong></div><div class="ficha-item"><small>E-mail</small><strong><?=e($r['student_email']?:'—')?></strong></div><div class="ficha-item"><small>Instrumento / ala</small><strong><?=e($r['instrument'])?></strong></div><div class="ficha-item"><small>Emergência</small><strong><?=e(($r['emergency_name']?:'—').' · '.($r['emergency_phone']?:'—'))?></strong></div><div class="ficha-item span2"><small>Endereço</small><strong><?=e(trim($r['address'].' — '.$r['neighborhood'].' — '.$r['city'],' —'))?></strong></div><div class="ficha-item span2"><small>Experiência / observações informadas</small><strong><?=e($r['experience']?:'—')?></strong></div></div></section>
<?php if($minor):?><section class="a4-section"><h2>Responsável legal / acompanhante</h2><?php if(trim((string)$r['guardian_photo_path'])!==''):?><img class="ficha-guardian-photo" src="../<?=e($r['guardian_photo_path'])?>" alt="Foto do responsável"><?php endif;?><div class="ficha-grid"><div class="ficha-item"><small>Nome completo</small><strong><?=e($r['guardian_name']?:'—')?></strong></div><div class="ficha-item"><small>Vínculo</small><strong><?=e($r['guardian_relationship']?:'—')?></strong></div><div class="ficha-item"><small>Nascimento</small><strong><?=e(ficha_date((string)$r['guardian_birth_date']))?></strong></div><div class="ficha-item"><small>CPF</small><strong><?=e($r['guardian_cpf']?:'—')?></strong></div><div class="ficha-item"><small>Telefone</small><strong><?=e($r['guardian_phone']?:'—')?></strong></div><div class="ficha-item"><small>E-mail</small><strong><?=e($r['guardian_email']?:'—')?></strong></div><div class="ficha-item span2"><small>Endereço</small><strong><?=e(trim($r['guardian_address'].' — '.$r['guardian_neighborhood'].' — '.$r['guardian_city'],' —'))?></strong></div></div><div style="clear:both"></div></section><?php endif;?>
<section class="a4-section"><h2>Estudo e trabalho</h2><div class="ficha-grid"><div class="ficha-item"><small>Situação escolar</small><strong><?=(int)$r['currently_studying']===1?e(school_network_label((string)$r['school_network'])):'NÃO ESTUDA ATUALMENTE'?></strong></div><div class="ficha-item"><small>Escola</small><strong><?=e($r['school_name']?:'—')?></strong></div><div class="ficha-item"><small>Situação profissional</small><strong><?=(int)$r['works_currently']===1?'TRABALHA ATUALMENTE':'NÃO TRABALHA ATUALMENTE'?></strong></div><div class="ficha-item"><small>Empresa / empregador</small><strong><?=e($r['employer_name']?:'—')?></strong></div></div></section>
<section class="a4-section ficha-terms"><h2>Autorizações e registros</h2><p><strong>Participação:</strong> <?=((int)$r['participation_authorization']===1?'AUTORIZADA':'NÃO REGISTRADA')?></p><p><strong>Imagem e voz:</strong> <?=((int)$r['image_authorization']===1?'AUTORIZADO':'NÃO AUTORIZADO')?></p><p><strong>Compromisso com instrumentos/patrimônio:</strong> <?=((int)$r['instrument_commitment']===1?'REGISTRADO':'NÃO REGISTRADO')?></p><p><strong>Compromisso com uniforme:</strong> <?=((int)$r['uniform_commitment']===1?'REGISTRADO':'NÃO REGISTRADO')?></p><p><strong>Privacidade:</strong> <?=((int)$r['privacy_ack']===1?'CIÊNCIA REGISTRADA':'NÃO REGISTRADA')?></p><p><strong>Nome de uso autorizado:</strong> <?=e(display_person_name((string)$r['student_name'],(string)$r['preferred_name']))?></p></section>
<section class="a4-signatures"><div class="a4-signature"><div class="line"></div><strong>COORDENADOR GERAL</strong></div><div class="a4-signature"><div class="line"></div><strong>INSTRUTOR RESPONSÁVEL</strong></div><div class="a4-signature"><div class="line"></div><strong>SECRETÁRIO(A)</strong></div></section><div class="ficha-signature-main"><div class="line"></div><strong><?=e($minor?'RESPONSÁVEL LEGAL — '.$signer:'PARTICIPANTE — '.$signer)?></strong></div><footer class="a4-footer">Ficha gerada em <?=date('d/m/Y H:i')?> · <?=e(report_location_line())?></footer></main></body></html>
