<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$year=(int)($_GET['year']??date('Y'));if($year<2020||$year>2100)$year=(int)date('Y');$type=strtoupper(trim((string)($_GET['type']??'TODOS')));$validTypes=['TODOS','ALUNO','INSTRUTOR','EQUIPE','ACOMPANHANTE'];if(!in_array($type,$validTypes,true))$type='TODOS';
$st=$pdo->prepare("SELECT * FROM attendance_events WHERE substr(event_date,1,4)=? ORDER BY event_date,id");$st->execute([(string)$year]);$events=$st->fetchAll();$stats=[];
foreach($events as $ev){$expected=attendance_expected_people($ev);$expectedKeys=[];foreach($expected as $p){if($type!=='TODOS'&&$p['type']!==$type)continue;$k=$p['type'].':'.$p['id'];$expectedKeys[$k]=true;if(!isset($stats[$k]))$stats[$k]=['person'=>$p,'total'=>0,'complete'=>0,'pending'=>0,'absent'=>0];$stats[$k]['total']++;}
 $cs=$pdo->prepare("SELECT person_type,person_id,check_type,scanned_at FROM attendance_checks WHERE event_id=?");$cs->execute([(int)$ev['id']]);$marks=[];foreach($cs->fetchAll() as $c){$k=$c['person_type'].':'.$c['person_id'];if($type!=='TODOS'&&$c['person_type']!==$type)continue;$marks[$k][$c['check_type']]=$c['scanned_at'];if(!isset($stats[$k])){$p=attendance_identity_by_type_id($c['person_type'],(int)$c['person_id']);if(!$p)continue;$stats[$k]=['person'=>$p,'total'=>0,'complete'=>0,'pending'=>0,'absent'=>0];}}
 foreach($expectedKeys as $k=>$_){$en=!empty($marks[$k]['ENTRADA']);$ex=!empty($marks[$k]['SAIDA']);if($en&&$ex)$stats[$k]['complete']++;elseif($en)$stats[$k]['pending']++;else$stats[$k]['absent']++;}
 foreach($marks as $k=>$m){if(isset($expectedKeys[$k])||!isset($stats[$k]))continue;$stats[$k]['total']++;$en=!empty($m['ENTRADA']);$ex=!empty($m['SAIDA']);if($en&&$ex)$stats[$k]['complete']++;elseif($en)$stats[$k]['pending']++;}
}
$rows=array_values($stats);foreach($rows as &$r){$r['percentage']=$r['total']>0?round(($r['complete']/$r['total'])*100,1):0;}unset($r);usort($rows,fn($a,$b)=>[$a['person']['type'],mb_strtolower($a['person']['name'])]<=>[$b['person']['type'],mb_strtolower($b['person']['name'])]);
admin_header('Frequência Geral — QR');$years=$pdo->query("SELECT DISTINCT substr(event_date,1,4) y FROM attendance_events WHERE event_date<>'' ORDER BY y DESC")->fetchAll();?>
<section class="panel"><div class="panel-heading-flex"><div><span>HISTÓRICO DE PRESENÇA</span><h2>Frequência anual por QR</h2><p>Presença completa exige duas marcações: <strong>ENTRADA + SAÍDA</strong>. Entrada sem saída aparece separadamente e não conta como presença completa.</p></div><a class="primary-link-admin" href="presenca_leitor.php">ABRIR LEITOR GERAL</a></div><form method="get" class="grid2"><label>Ano<select name="year"><option><?=$year?></option><?php foreach($years as $y):if((int)$y['y']===$year)continue;?><option><?=e($y['y'])?></option><?php endforeach;?></select></label><label>Grupo<select name="type"><?php foreach($validTypes as $x):?><option value="<?=$x?>" <?=$type===$x?'selected':''?>><?=$x==='TODOS'?'TODOS':($x==='INSTRUTOR'?'INSTRUTORES / AUXILIARES':$x)?></option><?php endforeach;?></select></label><button class="small-button">FILTRAR</button></form></section>
<section class="panel"><div class="panel-heading-flex"><div><h2>Frequência <?=$year?></h2><p><?=count($events)?> atividade(s) registrada(s) no ano.</p></div></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Tipo</th><th>Nome</th><th>Código/Matrícula</th><th>Função/Ala</th><th>Atividades</th><th>Completas</th><th>Saída pendente</th><th>Ausências</th><th>Frequência</th></tr></thead><tbody><?php foreach($rows as $r):$p=$r['person'];?><tr><td><strong><?=e($p['type'])?></strong></td><td><?=e(display_person_name($p['name'],$p['preferred']??''))?></td><td><?=e($p['number'])?></td><td><?=e($p['role'])?></td><td><?=$r['total']?></td><td class="present-ok"><strong><?=$r['complete']?></strong></td><td><?=$r['pending']?></td><td class="absent-no"><strong><?=$r['absent']?></strong></td><td><strong><?=e(number_format((float)$r['percentage'],1,',','.'))?>%</strong></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="9" class="empty-cell">Nenhum histórico encontrado para este filtro.</td></tr><?php endif;?></tbody></table></div></section>
<?php admin_footer(); ?>
