<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$err='';$ok='';
$st=$pdo->prepare("SELECT * FROM admins WHERE id=?");$st->execute([(int)$u['id']]);$r=$st->fetch();
if($_SERVER['REQUEST_METHOD']==='POST'){try{csrf_check();$name=trim((string)($_POST['display_name']??''));$birth=trim((string)($_POST['birth_date']??''));$cpf=normalize_cpf((string)($_POST['cpf']??''));$current=(string)($_POST['current_password']??'');if(!$r||!password_verify($current,$r['password_hash']))throw new RuntimeException('Informe sua senha atual corretamente para salvar os dados de recuperação.');if(mb_strlen($name)<3)throw new RuntimeException('Informe seu nome completo.');if(birth_age($birth)<18)throw new RuntimeException('Informe uma data de nascimento válida.');if(!cpf_valid($cpf))throw new RuntimeException('Informe um CPF válido.');$pdo->prepare("UPDATE admins SET display_name=?,birth_date=?,cpf=? WHERE id=?")->execute([$name,$birth,$cpf,(int)$u['id']]);$ok='Dados de recuperação atualizados com segurança.';$st=$pdo->prepare("SELECT * FROM admins WHERE id=?");$st->execute([(int)$u['id']]);$r=$st->fetch();}catch(Throwable $e){$err=$e->getMessage();}}
admin_header('Minha Conta');?>
<?php if($ok):?><div class="alert ok"><?=e($ok)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="panel account-recovery-panel"><div class="panel-heading-flex"><div><span>SEGURANÇA DA CONTA</span><h2>Dados para “Esqueci minha senha”</h2><p>A recuperação usa a combinação exata de <strong>nome completo + data de nascimento + CPF</strong>. Para alterar esses dados, confirme sua senha atual.</p></div><span class="<?=admin_recovery_ready((int)$u['id'])?'card-active':'card-inactive'?>"><?=admin_recovery_ready((int)$u['id'])?'RECUPERAÇÃO CONFIGURADA':'CONFIGURAÇÃO PENDENTE'?></span></div>
<form method="post" class="form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="grid2"><label>Nome completo<input name="display_name" value="<?=e($r['display_name']??'')?>" required></label><label>Data de nascimento<input type="date" name="birth_date" value="<?=e($r['birth_date']??'')?>" required></label><label>CPF<input name="cpf" value="<?=e($r['cpf']??'')?>" inputmode="numeric" required></label><label>Senha atual<input type="password" name="current_password" autocomplete="current-password" required></label></div><button class="primary">SALVAR DADOS DE RECUPERAÇÃO</button></form></section>
<?php admin_footer();?>
