<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$err='';$ajax=($_POST['ajax']??'')==='1';
function pl_event(int $id): ?array { $st=db()->prepare("SELECT * FROM attendance_events WHERE id=?");$st->execute([$id]);return $st->fetch()?:null; }
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  csrf_check();$action=(string)($_POST['action']??'');
  if($action==='create_event'){
    $title=trim((string)($_POST['title']??''));$type=trim((string)($_POST['event_type']??'ENSAIO'));$date=trim((string)($_POST['event_date']??today_bamab_date()));
    $start=trim((string)($_POST['start_time']??''));$end=trim((string)($_POST['end_time']??''));$notes=trim((string)($_POST['notes']??''));
    $allowedTypes=['ENSAIO','REUNIÃO','APRESENTAÇÃO','CAMPEONATO','EVENTO ESPECIAL'];if(!in_array($type,$allowedTypes,true))throw new RuntimeException('Tipo de atividade inválido.');
    if(mb_strlen($title)<3)throw new RuntimeException('Informe o nome da atividade.');if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new RuntimeException('Informe uma data válida.');
    $areas=array_values(array_intersect(enrollment_instruments(),array_map('strval',$_POST['areas']??[])));
    $students=isset($_POST['include_students'])?1:0;$instructors=isset($_POST['include_instructors'])?1:0;$team=isset($_POST['include_team'])?1:0;$companions=isset($_POST['include_companions'])?1:0;
    if(!$students&&!$instructors&&!$team&&!$companions)throw new RuntimeException('Selecione pelo menos um grupo para o controle de presença.');
    $pdo->beginTransaction();
    $pdo->prepare("INSERT INTO attendance_events(title,event_date,start_time,end_time,active,notes,created_at,created_by,event_type,control_mode,include_students,include_instructors,include_team,include_companions) VALUES(?,?,?,?,1,?,?,?,?, 'GERAL_DUAL',?,?,?,?)")
        ->execute([$title,$date,$start,$end,$notes,now_iso(),(int)$u['id'],$type,$students,$instructors,$team,$companions]);
    $eventId=(int)$pdo->lastInsertId();$ia=$pdo->prepare("INSERT INTO attendance_event_areas(event_id,area) VALUES(?,?)");foreach($areas as $area)$ia->execute([$eventId,$area]);
    $pdo->prepare("INSERT INTO attendance_general_controls(event_id,phase,updated_at,last_admin_id) VALUES(?,'FECHADO',?,?)")->execute([$eventId,now_iso(),(int)$u['id']]);$pdo->commit();
    go('presenca_leitor.php?event_id='.$eventId,'Atividade criada. Abra a ENTRADA quando estiver pronto para registrar os QR Codes.');
  }
  if(in_array($action,['open_entry','close_entry','open_exit','close_exit'],true)){
    $eventId=(int)($_POST['event_id']??0);$event=pl_event($eventId);if(!$event)throw new RuntimeException('Atividade não encontrada.');$msg=attendance_general_set_phase($eventId,$action,(int)$u['id']);go('presenca_leitor.php?event_id='.$eventId,$msg);
  }
  if($action==='reset_event'){
    if(!is_general_admin($u))throw new RuntimeException('Somente o Admin Geral pode reiniciar uma atividade.');$eventId=(int)($_POST['event_id']??0);$event=pl_event($eventId);if(!$event)throw new RuntimeException('Atividade não encontrada.');
    $pdo->beginTransaction();$pdo->prepare("DELETE FROM attendance_checks WHERE event_id=?")->execute([$eventId]);$pdo->prepare("DELETE FROM attendance_roster WHERE event_id=?")->execute([$eventId]);$pdo->prepare("UPDATE attendance_general_controls SET phase='FECHADO',entry_opened_at=NULL,entry_closed_at=NULL,exit_opened_at=NULL,exit_closed_at=NULL,last_admin_id=?,updated_at=? WHERE event_id=?")->execute([(int)$u['id'],now_iso(),$eventId]);$pdo->prepare("UPDATE attendance_events SET active=1,closed_at=NULL,roster_frozen_at='' WHERE id=?")->execute([$eventId]);$pdo->commit();go('presenca_leitor.php?event_id='.$eventId,'Atividade reiniciada e leituras apagadas.');
  }
  if($action==='scan'){
    $eventId=(int)($_POST['event_id']??0);$event=pl_event($eventId);if(!$event)throw new RuntimeException('Atividade não encontrada.');if((int)$event['active']!==1)throw new RuntimeException('Esta atividade está encerrada.');$control=attendance_general_control($eventId);$phase=(string)$control['phase'];
    if(!in_array($phase,['ENTRADA','SAIDA'],true))throw new RuntimeException('A leitura está fechada. Abra ENTRADA ou SAÍDA.');$checkType=$phase==='ENTRADA'?'ENTRADA':'SAIDA';
    $payload=trim((string)($_POST['payload']??''));$number=trim((string)($_POST['number']??''));$identity=$payload!==''?attendance_identity_from_payload($payload):null;if(!$identity&&$number!=='')$identity=attendance_identity_from_number($number);if(!$identity)throw new RuntimeException('QR ou código não reconhecido.');
    $reg=attendance_register_check($event,$identity,$checkType,$payload!==''?'QR':'MANUAL',(int)$u['id'],null);$name=display_person_name((string)$identity['name'],(string)($identity['preferred']??''));
    $response=['ok'=>true,'duplicate'=>$reg['duplicate'],'message'=>$reg['duplicate']?$checkType.' já registrada às '.$reg['time'].'.':$checkType.' REGISTRADA','person'=>['type'=>$identity['type'],'name'=>$name,'number'=>$identity['number'],'role'=>$identity['role'],'area'=>$reg['area']],'check_type'=>$checkType,'time'=>$reg['time']];
    if($ajax){header('Content-Type: application/json; charset=UTF-8');echo json_encode($response,JSON_UNESCAPED_UNICODE);exit;}
  }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if($ajax){http_response_code(400);header('Content-Type: application/json; charset=UTF-8');echo json_encode(['ok'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);exit;}$err=$e->getMessage();}
}
$eventId=(int)($_GET['event_id']??0);if($eventId<=0){$st=$pdo->prepare("SELECT id FROM attendance_events WHERE event_date=? AND active=1 ORDER BY id DESC LIMIT 1");$st->execute([today_bamab_date()]);$eventId=(int)($st->fetchColumn()?:0);} $event=$eventId?pl_event($eventId):null;$control=$event?attendance_general_control($eventId):null;
$events=$pdo->query("SELECT ae.*,(SELECT COUNT(*) FROM attendance_checks ac WHERE ac.event_id=ae.id AND ac.check_type='ENTRADA') entries,(SELECT COUNT(*) FROM attendance_checks ac WHERE ac.event_id=ae.id AND ac.check_type='SAIDA') exits FROM attendance_events ae ORDER BY ae.event_date DESC,ae.id DESC LIMIT 120")->fetchAll();
$recent=[];$entryCount=$exitCount=0;if($event){$st=$pdo->prepare("SELECT * FROM attendance_checks WHERE event_id=? ORDER BY scanned_at DESC,id DESC LIMIT 30");$st->execute([$eventId]);foreach($st->fetchAll() as $c){$idn=attendance_identity_by_type_id((string)$c['person_type'],(int)$c['person_id']);$c['identity']=$idn;$recent[]=$c;}$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_checks WHERE event_id=? AND check_type='ENTRADA'");$st->execute([$eventId]);$entryCount=(int)$st->fetchColumn();$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_checks WHERE event_id=? AND check_type='SAIDA'");$st->execute([$eventId]);$exitCount=(int)$st->fetchColumn();}
admin_header('Leitor Geral QR — Entrada e Saída');$msg=flash();$types=['ENSAIO','REUNIÃO','APRESENTAÇÃO','CAMPEONATO','EVENTO ESPECIAL'];
?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="panel qr-total-intro"><div class="panel-heading-flex"><div><span>CONTROLE OFICIAL DE PRESENÇA</span><h2>QR = Entrada + Saída + Frequência</h2><p>O mesmo QR permanente identifica aluno, instrutor/auxiliar, equipe e acompanhante. O sistema confere se o cadastro/documento está ativo antes de aceitar a marcação.</p></div><div class="professor-quick-actions"><a class="primary-link-admin" href="presenca.php">PROGRAMAÇÃO POR ALA</a><a class="primary-link-admin dark" href="frequencia_geral.php">FREQUÊNCIA GERAL</a></div></div></section>
<section class="panel"><h2>Criar atividade para controle QR</h2><form method="post" class="form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_event"><div class="grid2"><label>Nome da atividade<input name="title" placeholder="Ex.: Reunião Geral da BAMAB" required></label><label>Tipo<select name="event_type"><?php foreach($types as $x):?><option><?=e($x)?></option><?php endforeach;?></select></label><label>Data<input type="date" name="event_date" value="<?=e(today_bamab_date())?>" required></label><label>Hora inicial<input type="time" name="start_time"></label><label>Hora final<input type="time" name="end_time"></label><label>Observação<input name="notes"></label></div><h3>Quem deve marcar presença?</h3><div class="presence-audience-grid"><label class="check area-check"><input type="checkbox" name="include_students" checked> ALUNOS</label><label class="check area-check"><input type="checkbox" name="include_instructors" checked> INSTRUTORES / AUXILIARES</label><label class="check area-check"><input type="checkbox" name="include_team" checked> EQUIPE BAMAB</label><label class="check area-check"><input type="checkbox" name="include_companions"> ACOMPANHANTES / RESPONSÁVEIS</label></div><h3>Alas participantes <small>(deixe todas desmarcadas para atividade geral)</small></h3><div class="instructor-area-grid"><?php foreach(enrollment_instruments() as $area):?><label class="check area-check"><input type="checkbox" name="areas[]" value="<?=e($area)?>"> <?=e($area)?></label><?php endforeach;?></div><button class="primary">CRIAR ATIVIDADE DE PRESENÇA</button></form></section>
<section class="panel"><h2>Atividades recentes</h2><div class="attendance-event-list"><?php foreach($events as $ev):?><article class="<?=$eventId===(int)$ev['id']?'active-event':''?>"><div><strong><?=e($ev['title'])?></strong><small><?=e($ev['event_type'])?> · <?=e(date('d/m/Y',strtotime($ev['event_date'])))?> · Entradas: <?=$ev['entries']?> · Saídas: <?=$ev['exits']?></small></div><a class="small-button" href="?event_id=<?=$ev['id']?>">ABRIR LEITOR</a><a class="small-button" href="presenca_geral_relatorio.php?event_id=<?=$ev['id']?>">RELATÓRIO</a><span></span></article><?php endforeach;?><?php if(!$events):?><div class="empty-cell">Nenhuma atividade registrada.</div><?php endif;?></div></section>
<?php if($event):$aud=attendance_event_audience($event);$eventAreas=attendance_event_areas($eventId);?>
<section class="panel scanner-panel qr-general-live"><div class="scanner-head"><div><span><?=e($event['event_type'])?> · <?=e(date('d/m/Y',strtotime($event['event_date'])))?></span><h2><?=e($event['title'])?></h2><small><?=e($eventAreas?implode(' • ',$eventAreas):'TODAS AS ALAS')?> · <?=implode(' · ',array_keys(array_filter($aud)))?></small></div><div class="area-live-numbers"><b>ENTRADA <?=$entryCount?></b><b>SAÍDA <?=$exitCount?></b></div></div>
<div class="phase-controller admin-general-phase"><div class="phase-current"><span>ETAPA ATUAL</span><strong><?=e(attendance_phase_label((string)$control['phase']))?></strong></div><div class="phase-buttons"><?php if($control['phase']==='FECHADO'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="open_entry"><input type="hidden" name="event_id" value="<?=$eventId?>"><button class="phase-entry">ABRIR ENTRADA</button></form><?php elseif($control['phase']==='ENTRADA'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close_entry"><input type="hidden" name="event_id" value="<?=$eventId?>"><button class="phase-stop">ENCERRAR ENTRADA</button></form><?php elseif($control['phase']==='INTERVALO'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="open_exit"><input type="hidden" name="event_id" value="<?=$eventId?>"><button class="phase-exit">ABRIR SAÍDA</button></form><?php elseif($control['phase']==='SAIDA'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close_exit"><input type="hidden" name="event_id" value="<?=$eventId?>"><button class="phase-stop">CONCLUIR ATIVIDADE</button></form><?php endif;?></div></div>
<?php if(in_array($control['phase'],['ENTRADA','SAIDA'],true)):?><div class="scanner-mode <?=$control['phase']==='ENTRADA'?'entry-mode':'exit-mode'?>"><?=$control['phase']==='ENTRADA'?'LEITURA DE ENTRADA':'LEITURA DE SAÍDA'?></div><div class="scanner-grid"><div class="camera-box"><video id="qrVideo" playsinline muted></video><div id="cameraMessage">Clique em ABRIR CÂMERA e autorize o acesso.</div></div><div class="scan-result" id="scanResult"><strong>AGUARDANDO QR</strong><span>Aluno · Instrutor/Auxiliar · Equipe · Acompanhante</span></div></div><div class="scanner-actions"><button type="button" class="primary" id="startCamera">ABRIR CÂMERA</button><button type="button" class="small-button" id="stopCamera">PARAR</button></div><p class="muted qr-camera-note"><strong>CELULAR:</strong> em acesso por IP local do XAMPP usando HTTP, alguns navegadores podem bloquear a câmera por segurança. Nesse caso, use o código manual abaixo. Em acesso HTTPS, a câmera funciona quando o navegador oferece suporte ao leitor QR.</p><form id="manualPresence" class="manual-presence"><label>Código manual<input id="manualNumber" placeholder="Matrícula, BAMAB-I-000001, código da equipe..."></label><button type="submit" class="small-button">REGISTRAR</button></form><?php else:?><div class="empty-cell">Abra a ENTRADA ou a SAÍDA para ativar o leitor QR.</div><?php endif;?></section>
<?php if(in_array($control['phase'],['ENTRADA','SAIDA'],true)):?><script>
(()=>{const csrf=<?=json_encode(csrf_token())?>,eventId=<?=$eventId?>,video=document.getElementById('qrVideo'),result=document.getElementById('scanResult'),msg=document.getElementById('cameraMessage');let stream=null,detector=null,running=false,last='',lastAt=0;const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function send(data){const body=new URLSearchParams({csrf,action:'scan',ajax:'1',event_id:String(eventId),...data});try{const r=await fetch('presenca_leitor.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.message||'Falha');result.className='scan-result success';result.innerHTML='<strong>'+esc(j.message)+'</strong><b>'+esc(j.person.name)+'</b><span>'+esc(j.person.type+' · '+j.person.number+' · '+j.person.role)+'</span><small>'+esc('Área: '+j.person.area+' · '+j.time)+'</small>';if(navigator.vibrate)navigator.vibrate(j.duplicate?[80]:[100,60,100]);}catch(e){result.className='scan-result failure';result.innerHTML='<strong>NÃO REGISTRADO</strong><span>'+esc(e.message)+'</span>';if(navigator.vibrate)navigator.vibrate([250]);}}async function loop(){if(!running||!detector)return;try{const codes=await detector.detect(video);if(codes.length){const raw=codes[0].rawValue||'';const now=Date.now();if(raw&&(raw!==last||now-lastAt>3000)){last=raw;lastAt=now;await send({payload:raw});}}}catch(e){}setTimeout(loop,280)}document.getElementById('startCamera').onclick=async()=>{try{if(!('BarcodeDetector'in window))throw new Error('Leitura automática não disponível. Use Chrome/Edge atualizado ou o código manual.');detector=new BarcodeDetector({formats:['qr_code']});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();running=true;msg.textContent='Câmera ativa — aproxime o QR.';loop();}catch(e){msg.textContent=e.message}};document.getElementById('stopCamera').onclick=()=>{running=false;if(stream)stream.getTracks().forEach(t=>t.stop());video.srcObject=null;msg.textContent='Câmera parada.'};document.getElementById('manualPresence').onsubmit=async e=>{e.preventDefault();const number=document.getElementById('manualNumber').value.trim();if(number){await send({number});document.getElementById('manualNumber').select();}};})();
</script><?php endif;?>
<section class="panel"><div class="panel-heading-flex"><div><h2>Últimas marcações</h2><p>Leituras mais recentes desta atividade.</p></div><a class="small-button" href="presenca_geral_relatorio.php?event_id=<?=$eventId?>">RELATÓRIO COMPLETO</a></div><div class="recent-checks admin-recent-checks"><?php foreach($recent as $r):$i=$r['identity'];?><div><span class="<?=$r['check_type']==='ENTRADA'?'check-entry':'check-exit'?>"><?=e($r['check_type'])?></span><strong><?=e($i?display_person_name((string)$i['name'],(string)($i['preferred']??'')):'Cadastro #'.$r['person_id'])?></strong><small><?=e($r['person_type'])?> · <?=e($i['number']??'')?> · <?=e(date('H:i:s',strtotime($r['scanned_at'])))?></small></div><?php endforeach;?><?php if(!$recent):?><p>Nenhuma leitura ainda.</p><?php endif;?></div><?php if(is_general_admin($u)):?><form method="post" onsubmit="return confirm('Reiniciar esta atividade? Todas as marcações desta atividade serão apagadas.');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="reset_event"><input type="hidden" name="event_id" value="<?=$eventId?>"><button class="danger-soft">REINICIAR ESTA ATIVIDADE</button></form><?php endif;?></section>
<?php endif;?>
<?php admin_footer(); ?>
