<?php
require __DIR__.'/../config.php';require __DIR__.'/../report_helpers.php';$u=require_admin();$pdo=db();$id=(int)($_GET['event_id']??0);$st=$pdo->prepare("SELECT * FROM attendance_events WHERE id=?");$st->execute([$id]);$event=$st->fetch();if(!$event){http_response_code(404);exit('Atividade não encontrada.');}
$people=attendance_expected_people($event);$peopleMap=[];foreach($people as $p)$peopleMap[$p['type'].':'.$p['id']]=$p;
$st=$pdo->prepare("SELECT * FROM attendance_checks WHERE event_id=? ORDER BY scanned_at,id");$st->execute([$id]);$checks=[];foreach($st->fetchAll() as $c){$k=$c['person_type'].':'.$c['person_id'];$checks[$k][$c['check_type']]=$c;if(!isset($peopleMap[$k])){$x=attendance_identity_by_type_id((string)$c['person_type'],(int)$c['person_id']);if($x)$peopleMap[$k]=$x;}}
$rows=[];$complete=$pending=$absent=0;foreach($peopleMap as $k=>$p){$en=$checks[$k]['ENTRADA']??null;$ex=$checks[$k]['SAIDA']??null;$status=$en&&$ex?'PRESENÇA COMPLETA':($en?'SAÍDA PENDENTE':'AUSENTE');if($status==='PRESENÇA COMPLETA')$complete++;elseif($status==='SAÍDA PENDENTE')$pending++;else$absent++;$p['entry']=$en['scanned_at']??'';$p['exit']=$ex['scanned_at']??'';$p['status']=$status;$rows[]=$p;}
usort($rows,fn($a,$b)=>[$a['type'],mb_strtolower($a['name'])]<=>[$b['type'],mb_strtolower($b['name'])]);$groups=[];foreach($rows as $r)$groups[$r['type']][]=$r;
$export=(string)($_GET['export']??'');
if($export==='csv'){header('Content-Type:text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="presenca_geral_bamab_'.date('Y-m-d').'.csv"');echo "\xEF\xBB\xBF";$o=fopen('php://output','w');fputcsv($o,['Tipo','Nome','Código/Matrícula','Função/Ala','Entrada','Saída','Situação'],';');foreach($rows as $r)fputcsv($o,[$r['type'],display_person_name($r['name'],$r['preferred']??''),$r['number'],$r['role'], $r['entry']?date('H:i:s',strtotime($r['entry'])):'',$r['exit']?date('H:i:s',strtotime($r['exit'])):'',$r['status']],';');fclose($o);exit;}
if($export==='xls'){bamab_report_excel_headers('presenca_geral_bamab_'.date('Y-m-d').'.xls');$logo=bamab_report_logo_data_uri();echo '<!doctype html><html><head><meta charset="utf-8">'.bamab_report_excel_style_block().'</head><body><div class="sheet-wrap"><div class="sheet-head">'.($logo?'<img src="'.$logo.'" alt="Brasão">':'').'<div><h1>RELATÓRIO GERAL DE PRESENÇA</h1><p>'.e(report_location_line()).' · '.e($event['title']).' · '.e(date('d/m/Y',strtotime($event['event_date']))).'</p></div></div><div class="sheet-meta"><div><strong>'.$complete.'</strong><small>Presença completa</small></div><div><strong>'.$pending.'</strong><small>Saída pendente</small></div><div><strong>'.$absent.'</strong><small>Ausentes</small></div></div>';foreach($groups as $type=>$list){echo '<div class="sheet-block"><h2>'.e($type).'</h2><table class="sheet-table"><thead><tr><th>Nome</th><th>Código/Matrícula</th><th>Função/Ala</th><th>Entrada</th><th>Saída</th><th>Situação</th></tr></thead><tbody>';foreach($list as $r)echo '<tr><td>'.e(display_person_name($r['name'],$r['preferred']??'')).'</td><td>'.e($r['number']).'</td><td>'.e($r['role']).'</td><td>'.($r['entry']?e(date('H:i:s',strtotime($r['entry']))):'—').'</td><td>'.($r['exit']?e(date('H:i:s',strtotime($r['exit']))):'—').'</td><td>'.e($r['status']).'</td></tr>';echo '</tbody></table></div>';}echo '<div class="footer-note">Relatório gerado em '.date('d/m/Y H:i').'.</div></div></body></html>';exit;}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório Geral de Presença</title><link rel="stylesheet" href="../assets/report_a4.css"><?=bamab_report_style_block('../')?></head><body><div class="a4-toolbar no-print"><a href="presenca_leitor.php?event_id=<?=$id?>">← VOLTAR AO LEITOR</a><button onclick="window.print()">IMPRIMIR / PDF A4</button><a href="?event_id=<?=$id?>&export=xls">EXCEL</a><a href="?event_id=<?=$id?>&export=csv">CSV</a></div><main class="a4-document"><header class="a4-header"><img src="<?=e(bamab_report_logo_web('../'))?>" alt="Brasão"><div class="a4-location"><?=e(report_location_line())?></div></header><section class="a4-title"><h1>RELATÓRIO GERAL DE PRESENÇA</h1><p><?=e($event['title'])?> · <?=e($event['event_type'])?> · <?=e(date('d/m/Y',strtotime($event['event_date'])))?> · Presença completa = ENTRADA + SAÍDA</p></section><div class="a4-counts"><div><strong><?=$complete?></strong><span>Presença completa</span></div><div><strong><?=$pending?></strong><span>Saída pendente</span></div><div><strong><?=$absent?></strong><span>Ausentes</span></div></div>
<?php foreach($groups as $type=>$list):?><section class="a4-section"><h2><?=e($type==='INSTRUTOR'?'INSTRUTORES / AUXILIARES':$type)?></h2><table class="a4-table"><thead><tr><th>Nome</th><th>Código / Matrícula</th><th>Função / Ala</th><th>Entrada</th><th>Saída</th><th>Situação</th></tr></thead><tbody><?php foreach($list as $r):?><tr><td><?=e(display_person_name($r['name'],$r['preferred']??''))?></td><td><?=e($r['number'])?></td><td><?=e($r['role'])?></td><td><?=$r['entry']?e(date('H:i:s',strtotime($r['entry']))):'—'?></td><td><?=$r['exit']?e(date('H:i:s',strtotime($r['exit']))):'—'?></td><td><?=e($r['status'])?></td></tr><?php endforeach;?></tbody></table></section><?php endforeach;?>
<section class="a4-signatures"><div class="a4-signature"><div class="line"></div><strong>COORDENADOR GERAL</strong></div><div class="a4-signature"><div class="line"></div><strong>RESPONSÁVEL PELO CONTROLE</strong></div><div class="a4-signature"><div class="line"></div><strong>SECRETÁRIO(A)</strong></div></section><footer class="a4-footer">Relatório gerado em <?=date('d/m/Y H:i')?>.</footer></main></body></html>
