<?php
require __DIR__.'/_layout.php';$u=require_admin();$pdo=db();$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{csrf_check();$a=$_POST['action']??'';
  if($a==='create_schedule'){
   $title=trim((string)($_POST['title']??''));$type='ENSAIO';$weekday=(int)($_POST['weekday']??0);$start=trim((string)($_POST['start_time']??''));$end=trim((string)($_POST['end_time']??''));$notes=trim((string)($_POST['notes']??''));$areas=array_values(array_intersect(enrollment_instruments(),array_map('strval',$_POST['areas']??[])));$incStudents=isset($_POST['include_students'])?1:0;$incInstructors=isset($_POST['include_instructors'])?1:0;$incTeam=isset($_POST['include_team'])?1:0;$incCompanions=isset($_POST['include_companions'])?1:0;
   if(!in_array($title,bamab_rehearsal_names(),true))throw new RuntimeException('Selecione uma opção válida de ensaio.');if(!isset(bamab_weekdays()[$weekday]))throw new RuntimeException('Selecione um dia da semana.');if(!$areas)throw new RuntimeException('Selecione pelo menos uma ala participante.');
   if(!$incStudents&&!$incInstructors&&!$incTeam&&!$incCompanions)throw new RuntimeException('Selecione pelo menos um grupo para marcar presença.');$pdo->beginTransaction();$pdo->prepare("INSERT INTO attendance_schedules(title,event_type,weekday,start_time,end_time,notes,active,created_at,updated_at,created_by,include_students,include_instructors,include_team,include_companions) VALUES(?,?,?,?,?,?,1,?,?,?,?,?,?,?)")->execute([$title,$type,$weekday,$start,$end,$notes,now_iso(),now_iso(),(int)$u['id'],$incStudents,$incInstructors,$incTeam,$incCompanions]);$id=(int)$pdo->lastInsertId();$ia=$pdo->prepare("INSERT INTO attendance_schedule_areas(schedule_id,area) VALUES(?,?)");foreach($areas as $area)$ia->execute([$id,$area]);$pdo->commit();go('presenca.php','Programação semanal criada. A data será gerada automaticamente quando o instrutor entrar no dia escolhido.');
  }
  if($a==='toggle_schedule'){$id=(int)$_POST['schedule_id'];$active=(int)$_POST['active']===1?1:0;$pdo->prepare("UPDATE attendance_schedules SET active=?,updated_at=? WHERE id=?")->execute([$active,now_iso(),$id]);go('presenca.php',$active?'Programação ativada.':'Programação pausada.');}
  if($a==='delete_schedule'){if(!is_general_admin($u))throw new RuntimeException('Somente o Admin Geral pode excluir programações.');$id=(int)$_POST['schedule_id'];$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_events WHERE schedule_id=?");$st->execute([$id]);if((int)$st->fetchColumn()>0)throw new RuntimeException('Esta programação já possui histórico de presença. Para preservar os relatórios, apenas desative-a.');$pdo->prepare("DELETE FROM attendance_schedules WHERE id=?")->execute([$id]);go('presenca.php','Programação excluída.');}
  if($a==='delete_all_reports'){
   if(!is_general_admin($u))throw new RuntimeException('Somente o Admin Geral pode excluir todos os relatórios.');
   $confirm=trim((string)($_POST['confirm_delete']??''));
   if($confirm!=='EXCLUIR TODOS')throw new RuntimeException('Digite EXCLUIR TODOS para confirmar.');
   $pdo->beginTransaction();
   try{
     $pdo->exec("DELETE FROM attendance_checks");
     $pdo->exec("DELETE FROM attendance_records");
     $pdo->exec("DELETE FROM attendance_area_controls");
     $pdo->exec("DELETE FROM attendance_general_controls");
     $pdo->exec("DELETE FROM attendance_event_areas");
     $pdo->exec("DELETE FROM attendance_events");
     $pdo->commit();
   }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
   go('presenca.php','Todos os relatórios/históricos de ensaios foram excluídos. A programação semanal e os cadastros foram preservados.');
  }
  if($a==='close'){$id=(int)$_POST['event_id'];$now=now_iso();$pdo->prepare("UPDATE attendance_events SET active=0,closed_at=? WHERE id=?")->execute([$now,$id]);$pdo->prepare("UPDATE attendance_general_controls SET phase='CONCLUIDO',exit_closed_at=COALESCE(exit_closed_at,?),last_admin_id=?,updated_at=? WHERE event_id=?")->execute([$now,(int)$u['id'],$now,$id]);go('presenca.php?event_id='.$id,'Controle do dia encerrado.');}
  if($a==='reset_area'){if(!is_general_admin($u))throw new RuntimeException('Somente Admin Geral.');$id=(int)$_POST['event_id'];$area=(string)$_POST['area'];$pdo->prepare("DELETE FROM attendance_checks WHERE event_id=? AND area=? AND person_type='ALUNO'")->execute([$id,$area]);$pdo->prepare("UPDATE attendance_area_controls SET phase='FECHADO',entry_opened_at=NULL,entry_closed_at=NULL,exit_opened_at=NULL,exit_closed_at=NULL,last_instructor_id=NULL,updated_at=? WHERE event_id=? AND area=?")->execute([now_iso(),$id,$area]);go('presenca.php?event_id='.$id,'Controle da ala reiniciado.');}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$err=$e->getMessage();}
}
$days=bamab_weekdays();$schedules=$pdo->query("SELECT * FROM attendance_schedules ORDER BY weekday,start_time,title COLLATE NOCASE")->fetchAll();
$today=today_bamab_date();$todayWeek=today_bamab_weekday();$st=$pdo->prepare("SELECT ae.*,(SELECT COUNT(*) FROM attendance_checks ac WHERE ac.event_id=ae.id AND ac.check_type='ENTRADA') entries,(SELECT COUNT(*) FROM attendance_checks ac WHERE ac.event_id=ae.id AND ac.check_type='SAIDA') exits FROM attendance_events ae WHERE ae.event_date=? ORDER BY ae.start_time,ae.id");$st->execute([$today]);$todayEvents=$st->fetchAll();
$events=$pdo->query("SELECT ae.*,(SELECT COUNT(*) FROM attendance_checks ac WHERE ac.event_id=ae.id AND ac.check_type='ENTRADA') entries,(SELECT COUNT(*) FROM attendance_checks ac WHERE ac.event_id=ae.id AND ac.check_type='SAIDA') exits FROM attendance_events ae ORDER BY event_date DESC,id DESC LIMIT 100")->fetchAll();
$selectedId=(int)($_GET['event_id']??($todayEvents[0]['id']??($events[0]['id']??0)));$st=$pdo->prepare("SELECT * FROM attendance_events WHERE id=?");$st->execute([$selectedId]);$selected=$st->fetch()?:null;$selectedAreas=$selected?attendance_event_areas($selectedId):[];
admin_header('Presença por Ala — Programação Semanal');$msg=flash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="panel professor-access-panel"><div class="panel-heading-flex"><div><span>ACESSO RÁPIDO</span><h2>Controle de Presença BAMAB</h2><p>Use o controle por ala com os instrutores ou o Leitor Geral para registrar alunos, instrutores/auxiliares, equipe e acompanhantes em ensaios, reuniões e eventos.</p></div><div class="professor-quick-actions"><a class="primary-link-admin" href="presenca_leitor.php">LEITOR GERAL QR</a><a class="primary-link-admin dark" href="frequencia_geral.php">FREQUÊNCIA GERAL</a><a class="small-button" href="instrutores.php">GERENCIAR PROFESSORES</a><a class="small-button" href="../instrutor/login.php" target="_blank" rel="noopener noreferrer">ÁREA DO PROFESSOR</a></div></div></section>
<section class="panel"><div class="panel-heading-flex"><div><span>CONTROLE SIMPLIFICADO</span><h2>Ensaios por dia da semana</h2><p>Escolha o tipo de ensaio e o dia da semana. A data real é criada automaticamente quando o Professor/Instrutor entra naquele dia.</p></div></div><div class="today-date-admin"><span>HOJE</span><strong><?=e(bamab_weekday_label($todayWeek))?> · <?=e(date('d/m/Y'))?></strong></div></section>
<section class="panel"><h2>Criar programação semanal</h2><form method="post" class="form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_schedule"><div class="grid2"><label>Nome do ensaio<select name="title" required><option value="">SELECIONE</option><?php foreach(bamab_rehearsal_names() as $rn):?><option value="<?=e($rn)?>"><?=e($rn)?></option><?php endforeach;?></select></label><label>Dia da semana<select name="weekday" required><option value="">SELECIONE</option><?php foreach($days as $n=>$label):?><option value="<?=$n?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Hora inicial prevista<input type="time" name="start_time"></label><label>Hora final prevista<input type="time" name="end_time"></label><label>Observação<input name="notes"></label></div><h3>Quem deve marcar presença?</h3><div class="presence-audience-grid"><label class="check area-check"><input type="checkbox" name="include_students" checked> ALUNOS</label><label class="check area-check"><input type="checkbox" name="include_instructors" checked> INSTRUTORES / AUXILIARES</label><label class="check area-check"><input type="checkbox" name="include_team"> EQUIPE BAMAB</label><label class="check area-check"><input type="checkbox" name="include_companions"> ACOMPANHANTES</label></div><h3>Alas participantes</h3><div class="instructor-area-grid"><?php foreach(enrollment_instruments() as $area):?><label class="check area-check"><input type="checkbox" name="areas[]" value="<?=e($area)?>" checked> <?=e($area)?></label><?php endforeach;?></div><button class="primary">SALVAR PROGRAMAÇÃO SEMANAL</button></form></section>
<section class="panel"><h2>Programação semanal</h2><p>Essas programações permanecem cadastradas. Em cada semana, o sistema cria automaticamente a presença com a data daquele dia quando o primeiro instrutor responsável acessar sua área.</p><div class="weekly-schedule-grid"><?php foreach($schedules as $s):$areas=attendance_schedule_areas((int)$s['id']);?><article class="<?=$s['active']?'schedule-active':'schedule-paused'?>"><div class="schedule-day"><?=e(bamab_weekday_label((int)$s['weekday']))?></div><h3><?=e($s['title'])?></h3><p><?=e($s['event_type'])?><?= $s['start_time']?' · '.e($s['start_time']):''?><?= $s['end_time']?' às '.e($s['end_time']):''?></p><small><?=e(implode(' • ',$areas))?></small><small class="schedule-audience">Presença: <?=e(implode(' · ',array_filter([(int)($s['include_students']??1)?'ALUNOS':'',(int)($s['include_instructors']??1)?'INSTRUTORES/AUX.':'',(int)($s['include_team']??0)?'EQUIPE':'',(int)($s['include_companions']??0)?'ACOMPANHANTES':''])))?></small><div class="schedule-actions"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle_schedule"><input type="hidden" name="schedule_id" value="<?=$s['id']?>"><input type="hidden" name="active" value="<?=$s['active']?0:1?>"><button class="<?=$s['active']?'danger-soft':'activate-btn'?>"><?=$s['active']?'PAUSAR':'ATIVAR'?></button></form><?php if(is_general_admin($u)):?><form method="post" onsubmit="return confirm('Excluir esta programação semanal?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_schedule"><input type="hidden" name="schedule_id" value="<?=$s['id']?>"><button class="delete-period-btn">EXCLUIR</button></form><?php endif;?></div></article><?php endforeach;?><?php if(!$schedules):?><div class="empty-cell">Nenhuma programação semanal cadastrada.</div><?php endif;?></div></section>
<section class="panel"><div class="panel-heading-flex"><div><h2>Controles gerados hoje</h2><p><?=e(bamab_weekday_label($todayWeek))?>, <?=e(date('d/m/Y'))?>. Estes registros aparecem somente depois que um instrutor autorizado entra na área interna.</p></div><a class="small-button" href="../instrutor/login.php" target="_blank" rel="noopener noreferrer">LOGIN DOS INSTRUTORES</a></div><?php if($todayEvents):?><div class="attendance-event-list"><?php foreach($todayEvents as $ev):?><article class="<?=$ev['active']?'active-event':''?>"><div><strong><?=e($ev['title'])?></strong><small><?=e($ev['event_type'])?> · <?=e(date('d/m/Y',strtotime($ev['event_date'])))?> · Entrada: <?=$ev['entries']?> · Saída: <?=$ev['exits']?></small></div><a class="small-button" href="?event_id=<?=$ev['id']?>">ABRIR</a><a class="small-button" href="presenca_leitor.php?event_id=<?=$ev['id']?>">LEITOR GERAL</a><a class="small-button" href="presenca_relatorio.php?event_id=<?=$ev['id']?>">RELATÓRIO ALUNOS</a><a class="small-button" href="presenca_geral_relatorio.php?event_id=<?=$ev['id']?>">RELATÓRIO GERAL</a><a class="small-button" href="presenca_relatorio.php?event_id=<?=$ev['id']?>&export=xls">EXCEL</a><?php if($ev['active']):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close"><input type="hidden" name="event_id" value="<?=$ev['id']?>"><button class="danger-soft">ENCERRAR DIA</button></form><?php endif;?></article><?php endforeach;?></div><?php else:?><div class="empty-cell">Ainda não há controle gerado hoje. Ele será criado automaticamente quando um instrutor das alas programadas fizer login.</div><?php endif;?></section>
<?php if($selected&&in_array($selected['control_mode'],['ALA_DUAL','ALA_DUAL_WEEKDAY'],true)):?><section class="panel"><div class="panel-heading-flex"><div><h2><?=e($selected['title'])?></h2><p><?=e($selected['event_type'])?> · <?=e(date('d/m/Y',strtotime($selected['event_date'])))?><?= $selected['start_time']?' · '.e($selected['start_time']):''?><?= $selected['end_time']?' às '.e($selected['end_time']):''?></p></div><a class="admin-action-link" href="presenca_leitor.php?event_id=<?=$selectedId?>">LEITOR GERAL</a><a class="admin-action-link" href="presenca_relatorio.php?event_id=<?=$selectedId?>">RELATÓRIO POR ALA</a><a class="admin-action-link" href="presenca_geral_relatorio.php?event_id=<?=$selectedId?>">RELATÓRIO GERAL</a><a class="admin-action-link" href="presenca_relatorio.php?event_id=<?=$selectedId?>&export=xls">EXCEL</a></div><div class="area-control-admin-grid"><?php foreach($selectedAreas as $area):$c=attendance_area_control($selectedId,$area);$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_checks WHERE event_id=? AND area=? AND person_type='ALUNO' AND check_type='ENTRADA'");$st->execute([$selectedId,$area]);$en=(int)$st->fetchColumn();$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_checks WHERE event_id=? AND area=? AND person_type='ALUNO' AND check_type='SAIDA'");$st->execute([$selectedId,$area]);$ex=(int)$st->fetchColumn();$inst=$pdo->prepare("SELECT i.full_name,i.preferred_name,i.role FROM instructors i JOIN instructor_areas ia ON ia.instructor_id=i.id WHERE ia.area=? AND i.active=1 ORDER BY i.role,i.full_name");$inst->execute([$area]);$people=$inst->fetchAll();?><article><div><span><?=e($area)?></span><strong><?=e(attendance_phase_label($c['phase']))?></strong></div><div class="area-counts"><b>ENTRADA <?=$en?></b><b>SAÍDA <?=$ex?></b></div><small>Responsáveis: <?=e($people?implode(', ',array_map(fn($x)=>($x['preferred_name']?:$x['full_name']).' ('.$x['role'].')',$people)):'Nenhum instrutor atribuído')?></small><?php if(is_general_admin($u)):?><form method="post" onsubmit="return confirm('Reiniciar leituras desta ala?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="reset_area"><input type="hidden" name="event_id" value="<?=$selectedId?>"><input type="hidden" name="area" value="<?=e($area)?>"><button class="danger-soft">REINICIAR ALA</button></form><?php endif;?></article><?php endforeach;?></div></section><?php endif;?>
<section class="panel"><h2>Histórico</h2><div class="attendance-event-list"><?php foreach($events as $ev):?><article><div><strong><?=e($ev['title'])?></strong><small><?=e(date('d/m/Y',strtotime($ev['event_date'])))?> · Entrada: <?=$ev['entries']?> · Saída: <?=$ev['exits']?></small></div><a class="small-button" href="?event_id=<?=$ev['id']?>">ABRIR</a><a class="small-button" href="presenca_leitor.php?event_id=<?=$ev['id']?>">LEITOR GERAL</a><a class="small-button" href="presenca_relatorio.php?event_id=<?=$ev['id']?>">RELATÓRIO ALUNOS</a><a class="small-button" href="presenca_geral_relatorio.php?event_id=<?=$ev['id']?>">RELATÓRIO GERAL</a><a class="small-button" href="presenca_relatorio.php?event_id=<?=$ev['id']?>&export=xls">EXCEL</a></article><?php endforeach;?></div></section>

<?php if(is_general_admin($u)):?><section class="panel danger-zone reports-danger-zone"><h2>Excluir todos os relatórios de ensaios</h2><p>Use somente quando quiser limpar todo o histórico de presença. <strong>Alunos, instrutores, auxiliares e programação semanal NÃO serão excluídos.</strong></p><form method="post" class="delete-all-reports-form" onsubmit="return confirm('ATENÇÃO: todos os relatórios e leituras de presença serão apagados definitivamente. Confirma?');"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_all_reports"><label>Para confirmar, digite <strong>EXCLUIR TODOS</strong><input name="confirm_delete" placeholder="EXCLUIR TODOS" required></label><button class="danger">EXCLUIR TODOS OS RELATÓRIOS DE ENSAIOS</button></form></section><?php endif;?>
<?php admin_footer();?>
