<?php
require __DIR__.'/_layout.php';require __DIR__.'/_doc_helpers.php';
$u=require_admin();if(!is_general_admin($u)){http_response_code(403);exit('Somente o Admin Geral pode editar diplomas e certificados.');}
$pdo=db();$err='';$editId=(int)($_GET['edit_signer']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 csrf_check();
 try{
  $action=(string)($_POST['action']??'settings');
  if($action==='settings'){
   $keys=[
    'recognition_certificate_title','recognition_certificate_subtitle','recognition_certificate_body_student','recognition_certificate_dedication_student','recognition_certificate_body_team','recognition_certificate_dedication_team',
    'recognition_diploma_title','recognition_diploma_subtitle','recognition_diploma_body_student','recognition_diploma_dedication_student','recognition_diploma_body_team','recognition_diploma_dedication_team',
    'recognition_partner_certificate_title','recognition_partner_certificate_subtitle','recognition_certificate_body_partner','recognition_certificate_dedication_partner','recognition_certificate_body_institutional','recognition_certificate_dedication_institutional',
    'recognition_history_title','recognition_history_subtitle','recognition_history_note','recognition_footer_text','recognition_place_text'
   ];
   foreach($keys as $k)set_setting($k,bamab_doc_safe_text((string)($_POST[$k]??''),2400));
   set_setting('recognition_show_serial',isset($_POST['recognition_show_serial'])?'1':'0');
   go('reconhecimento_config.php','Modelos premium atualizados.');
  }
  if($action==='signer_delete'){
   $id=(int)($_POST['id']??0);$st=$pdo->prepare("SELECT signature_path FROM recognition_signers WHERE id=?");$st->execute([$id]);$old=(string)($st->fetchColumn()?:'');$pdo->prepare("DELETE FROM recognition_signers WHERE id=?")->execute([$id]);delete_local_media($old);go('reconhecimento_config.php','Assinante removido.');
  }
  if($action==='signer_toggle'){$id=(int)($_POST['id']??0);$pdo->prepare("UPDATE recognition_signers SET active=CASE active WHEN 1 THEN 0 ELSE 1 END,updated_at=? WHERE id=?")->execute([now_iso(),$id]);go('reconhecimento_config.php','Assinante atualizado.');}
  if($action==='signer_save'){
   $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$role=trim((string)($_POST['role']??''));$order=max(0,min(999,(int)($_POST['sort_order']??100)));$active=isset($_POST['active'])?1:0;if(mb_strlen($role)<3)throw new RuntimeException('Informe o cargo/função do assinante.');
   $old='';if($id){$st=$pdo->prepare("SELECT signature_path FROM recognition_signers WHERE id=?");$st->execute([$id]);$old=(string)($st->fetchColumn()?:'');}
   $path=$old;if(!empty($_FILES['signature']['name'])){$path=upload_file($_FILES['signature'],'image');if($old)delete_local_media($old);}$now=now_iso();
   if($id){$pdo->prepare("UPDATE recognition_signers SET name=?,role=?,signature_path=?,sort_order=?,active=?,updated_at=? WHERE id=?")->execute([$name,$role,$path,$order,$active,$now,$id]);}
   else{$pdo->prepare("INSERT INTO recognition_signers(name,role,signature_path,sort_order,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?)")->execute([$name,$role,$path,$order,$active,$now,$now]);}
   go('reconhecimento_config.php','Assinante salvo.');
  }
 }catch(Throwable $e){$err=$e->getMessage();}
}
$edit=null;if($editId){$st=$pdo->prepare("SELECT * FROM recognition_signers WHERE id=?");$st->execute([$editId]);$edit=$st->fetch()?:null;}$signers=recognition_signers(false);admin_header('Editor Premium de Diplomas e Certificados');$msg=flash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="panel recognition-editor-intro recognition-premium-intro"><div class="panel-heading-flex"><div><span>DOCUMENTOS OFICIAIS BAMAB · FRENTE E VERSO</span><h2>Diplomas, Certificados, Parceiros e Histórico Musical</h2><p>Todo o texto principal, dedicatórias, rodapé e assinaturas podem ser alterados pelo Admin. As cores continuam seguindo o Editor de Carteirinhas e Crachás. Alunos recebem no verso o histórico das notas finais do ano.</p></div><div><a class="small-button" href="documentos.php">EDITAR CORES</a><a class="small-button" href="reconhecimentos.php">EMITIR DOCUMENTOS</a></div></div></section>
<form method="post" class="panel form-stack recognition-premium-settings"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="settings">
<h2>Certificado — Aluno</h2><div class="grid2"><label>Título<input name="recognition_certificate_title" value="<?=e(setting('recognition_certificate_title'))?>"></label><label>Subtítulo<input name="recognition_certificate_subtitle" value="<?=e(setting('recognition_certificate_subtitle'))?>"><small>Use {ANO}.</small></label></div><label>Texto principal<textarea name="recognition_certificate_body_student" rows="5"><?=e(setting('recognition_certificate_body_student'))?></textarea></label><label>Dedicatória<textarea name="recognition_certificate_dedication_student" rows="4"><?=e(setting('recognition_certificate_dedication_student'))?></textarea></label>
<h2>Certificado — Equipe</h2><label>Texto principal<textarea name="recognition_certificate_body_team" rows="4"><?=e(setting('recognition_certificate_body_team'))?></textarea></label><label>Dedicatória<textarea name="recognition_certificate_dedication_team" rows="4"><?=e(setting('recognition_certificate_dedication_team'))?></textarea></label>
<h2>Diploma — Aluno</h2><div class="grid2"><label>Título<input name="recognition_diploma_title" value="<?=e(setting('recognition_diploma_title'))?>"></label><label>Subtítulo<input name="recognition_diploma_subtitle" value="<?=e(setting('recognition_diploma_subtitle'))?>"></label></div><label>Texto principal<textarea name="recognition_diploma_body_student" rows="5"><?=e(setting('recognition_diploma_body_student'))?></textarea></label><label>Dedicatória<textarea name="recognition_diploma_dedication_student" rows="4"><?=e(setting('recognition_diploma_dedication_student'))?></textarea></label>
<h2>Diploma — Equipe</h2><label>Texto principal<textarea name="recognition_diploma_body_team" rows="4"><?=e(setting('recognition_diploma_body_team'))?></textarea></label><label>Dedicatória<textarea name="recognition_diploma_dedication_team" rows="4"><?=e(setting('recognition_diploma_dedication_team'))?></textarea></label>
<h2>Certificado de Parceiro / Apoio Institucional</h2><div class="grid2"><label>Título<input name="recognition_partner_certificate_title" value="<?=e(setting('recognition_partner_certificate_title'))?>"></label><label>Subtítulo<input name="recognition_partner_certificate_subtitle" value="<?=e(setting('recognition_partner_certificate_subtitle'))?>"></label></div><label>Texto — Patrocinador/Apoiador/Idealizador/Parceiro<textarea name="recognition_certificate_body_partner" rows="4"><?=e(setting('recognition_certificate_body_partner'))?></textarea></label><label>Dedicatória — Parceiro<textarea name="recognition_certificate_dedication_partner" rows="4"><?=e(setting('recognition_certificate_dedication_partner'))?></textarea></label><label>Texto — Prefeitura/Secretaria/Órgão<textarea name="recognition_certificate_body_institutional" rows="4"><?=e(setting('recognition_certificate_body_institutional'))?></textarea></label><label>Dedicatória — Apoio Institucional<textarea name="recognition_certificate_dedication_institutional" rows="4"><?=e(setting('recognition_certificate_dedication_institutional'))?></textarea></label>
<h2>Verso — Histórico de Desenvolvimento Musical</h2><div class="grid2"><label>Título<input name="recognition_history_title" value="<?=e(setting('recognition_history_title'))?>"></label><label>Subtítulo<input name="recognition_history_subtitle" value="<?=e(setting('recognition_history_subtitle'))?>"></label></div><label>Observação do histórico<textarea name="recognition_history_note" rows="4"><?=e(setting('recognition_history_note'))?></textarea></label>
<div class="grid2"><label>Local de emissão<input name="recognition_place_text" value="<?=e(setting('recognition_place_text','Santa Luzia do Paruá — Maranhão'))?>"></label><label>Rodapé<input name="recognition_footer_text" value="<?=e(setting('recognition_footer_text'))?>"></label></div><p class="legal-note">Campos automáticos: <strong>{NOME}</strong>, <strong>{ANO}</strong>, <strong>{FUNCAO}</strong> e <strong>{MATRICULA}</strong>.</p><label class="checkline"><input type="checkbox" name="recognition_show_serial" <?=setting('recognition_show_serial','1')==='1'?'checked':''?>> Mostrar número de controle</label><button class="primary">SALVAR TODOS OS MODELOS</button></form>
<form method="post" enctype="multipart/form-data" class="panel form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="signer_save"><input type="hidden" name="id" value="<?=$edit?(int)$edit['id']:0?>"><h2><?=$edit?'Editar assinatura':'Adicionar assinatura'?></h2><p>Use aqui as autoridades mais importantes da equipe, Secretário(a) de Cultura, Prefeito(a) e outros responsáveis. O documento utiliza até <strong>4 assinaturas ativas</strong>, respeitando a ordem configurada.</p><div class="grid2"><label>Nome da autoridade / responsável<input name="name" value="<?=e($edit['name']??'')?>" placeholder="Nome completo"></label><label>Cargo / função<input name="role" value="<?=e($edit['role']??'')?>" placeholder="Ex.: PREFEITO(A) MUNICIPAL" required></label><label>Imagem da assinatura (opcional)<input type="file" name="signature" accept="image/png,image/jpeg,image/webp,image/gif"><small>PNG transparente dá o melhor resultado.</small></label><label>Ordem<input type="number" name="sort_order" min="0" max="999" value="<?=e((string)($edit['sort_order']??100))?>"></label></div><label class="checkline"><input type="checkbox" name="active" <?=!$edit||(int)$edit['active']===1?'checked':''?>> Mostrar esta assinatura</label><div class="form-actions"><button class="primary">SALVAR ASSINATURA</button><?php if($edit):?><a class="small-button" href="reconhecimento_config.php">CANCELAR</a><?php endif;?></div></form>
<section class="panel"><h2>Assinaturas configuradas</h2><div class="recognition-signer-list"><?php foreach($signers as $s):?><article class="recognition-signer-card <?=((int)$s['active']===1)?'':'is-inactive'?>"><div class="signer-preview"><?php if($s['signature_path']):?><img src="../<?=e($s['signature_path'])?>" alt="Assinatura de <?=e($s['name'])?>"><?php else:?><span>ASSINATURA</span><?php endif;?></div><div><strong><?=e($s['name']?:'NOME A DEFINIR')?></strong><span><?=e($s['role'])?></span><small>Ordem <?=(int)$s['sort_order']?> · <?=((int)$s['active']===1)?'ATIVA':'OCULTA'?></small></div><div class="contact-admin-actions"><a class="small-button" href="reconhecimento_config.php?edit_signer=<?=(int)$s['id']?>">EDITAR</a><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="signer_toggle"><input type="hidden" name="id" value="<?=(int)$s['id']?>"><button class="small-button"><?=((int)$s['active']===1)?'OCULTAR':'ATIVAR'?></button></form><form method="post" onsubmit="return confirm('Excluir esta assinatura?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="signer_delete"><input type="hidden" name="id" value="<?=(int)$s['id']?>"><button class="danger-soft">EXCLUIR</button></form></div></article><?php endforeach;?></div></section>
<?php admin_footer();?>
