<?php
require __DIR__.'/_layout.php';$u=require_instructor();$pdo=db();$testId=(int)($_GET['test_id']??$_POST['test_id']??0);$area=trim((string)($_GET['area']??$_POST['area']??''));$studentId=(int)($_GET['student_id']??$_POST['student_id']??0);$test=evaluation_test($testId);$student=evaluation_student($studentId);$err='';
if(!$test||!$student||$student['instrument']!==$area||(int)($test['owner_instructor_id']??0)!==(int)$u['id']||!instructor_has_area((int)$u['id'],$area)||!in_array($area,evaluation_test_areas($testId),true)){http_response_code(403);exit('Avaliação não autorizada.');}
if($test['status']!=='ABERTO'){header('Location: avaliacao_alunos.php?test_id='.$testId.'&area='.urlencode($area));exit;}
$criteria=evaluation_criteria($testId,$area);if(count($criteria)!==10)exit('Este teste precisa ter exatamente 10 critérios.');$existing=evaluation_submission($testId,$area,$studentId,(int)$u['id']);$existingScores=[];if($existing)foreach(evaluation_submission_scores((int)$existing['id']) as $x)$existingScores[(int)$x['criterion_id']]=(int)$x['score'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{csrf_check();$scores=$_POST['score']??[];$allowed=array_keys(evaluation_rating_options());$sum=0;$chosen=[];foreach($criteria as $c){$cid=(int)$c['id'];$score=(int)($scores[$cid]??0);if(!in_array($score,$allowed,true))throw new RuntimeException('Avalie todos os 10 critérios antes de finalizar.');$chosen[$cid]=$score;$sum+=$score;}$final=round($sum/10,1);$pdo->beginTransaction();$now=now_iso();$sub=evaluation_submission($testId,$area,$studentId,(int)$u['id']);if($sub){$sid=(int)$sub['id'];$pdo->prepare("UPDATE evaluation_submissions SET status='CONCLUIDA',final_score=?,total_points=?,completed_at=?,updated_at=? WHERE id=?")->execute([$final,$sum,$now,$now,$sid]);$pdo->prepare("DELETE FROM evaluation_scores WHERE submission_id=?")->execute([$sid]);}else{$pdo->prepare("INSERT INTO evaluation_submissions(test_id,area,student_id,instructor_id,status,final_score,total_points,completed_at,updated_at) VALUES(?,?,?,?,'CONCLUIDA',?,?,?,?)")->execute([$testId,$area,$studentId,(int)$u['id'],$final,$sum,$now,$now]);$sid=(int)$pdo->lastInsertId();}$ins=$pdo->prepare("INSERT INTO evaluation_scores(submission_id,criterion_id,rating,score) VALUES(?,?,?,?)");foreach($criteria as $c){$score=$chosen[(int)$c['id']];$ins->execute([$sid,(int)$c['id'],evaluation_rating_label($score),$score]);}$pdo->commit();igo('avaliacao_detalhe.php?id='.$sid,'Avaliação salva. Ela permanece na sua área até você finalizar o teste e enviar o relatório ao Admin.');
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$err=$e->getMessage();}
}
instructor_header('Avaliar Aluno');?>
<?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="evaluation-student-header"><span><?=e($area)?> · <?=e($student['registration_number'])?></span><h2><?=e(evaluation_student_name($student))?></h2><p><?=e($test['title'])?> · 10 critérios · máximo de 100 pontos</p></section>
<section class="evaluation-scoring-board" aria-live="polite"><div><span>RESPONDIDOS</span><strong id="answeredCount">0/10</strong></div><div><span>PONTOS</span><strong id="pointsCount">0/100</strong></div><div><span>NOTA PARCIAL</span><strong id="partialGrade">—</strong></div></section>
<div class="evaluation-score-legend"><b>REGULAR <em>5</em><small>pontos</small></b><b>BOM <em>8</em><small>pontos</small></b><b>ÓTIMO <em>9</em><small>pontos</small></b><b>EXCELENTE <em>10</em><small>pontos</small></b></div>
<form method="post" class="evaluation-form" id="evaluationForm"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="test_id" value="<?=$testId?>"><input type="hidden" name="area" value="<?=e($area)?>"><input type="hidden" name="student_id" value="<?=$studentId?>"><?php foreach($criteria as $i=>$c):?><fieldset class="evaluation-question"><legend><b><?=($i+1)?>.</b> <?=e($c['criterion'])?></legend><div class="rating-options"><?php foreach(evaluation_rating_options() as $points=>$label):?><label class="rating-<?=$points?>"><input type="radio" name="score[<?=$c['id']?>]" value="<?=$points?>" <?=($existingScores[(int)$c['id']]??0)===$points?'checked':''?> required><span><strong><?=e($label)?></strong><small><?=$points?> PONTOS</small></span></label><?php endforeach;?></div></fieldset><?php endforeach;?><div class="evaluation-submit-bar"><a class="instr-secondary" href="avaliacao_alunos.php?test_id=<?=$testId?>&area=<?=urlencode($area)?>">CANCELAR</a><button class="instr-primary">SALVAR AVALIAÇÃO DO ALUNO</button></div></form>
<script>
(()=>{const form=document.getElementById('evaluationForm'),answered=document.getElementById('answeredCount'),points=document.getElementById('pointsCount'),grade=document.getElementById('partialGrade');function update(){const checked=[...form.querySelectorAll('input[type=radio]:checked')],sum=checked.reduce((n,x)=>n+Number(x.value||0),0);answered.textContent=checked.length+'/10';points.textContent=sum+'/100';grade.textContent=checked.length?((sum/checked.length).toFixed(1).replace('.',',')+'/10'):'—';}form.addEventListener('change',update);update();})();
</script>
<?php instructor_footer();?>
