<?php
require __DIR__.'/_layout.php';$u=require_instructor();$pdo=db();$testId=(int)($_GET['test_id']??0);$area=trim((string)($_GET['area']??''));$test=evaluation_test($testId);
if(!$test||(int)($test['owner_instructor_id']??0)!==(int)$u['id']||!instructor_has_area((int)$u['id'],$area)||!in_array($area,evaluation_test_areas($testId),true)){http_response_code(403);exit('Teste ou ala não autorizado para este instrutor.');}
$st=$pdo->prepare("SELECT * FROM enrollments WHERE status='APROVADA' AND deleted_at IS NULL AND instrument=? ORDER BY student_name COLLATE NOCASE");$st->execute([$area]);$students=$st->fetchAll();
$st=$pdo->prepare("SELECT student_id,id,final_score,total_points FROM evaluation_submissions WHERE test_id=? AND area=? AND instructor_id=?");$st->execute([$testId,$area,(int)$u['id']]);$done=[];foreach($st->fetchAll() as $d)$done[(int)$d['student_id']]=$d;
instructor_header('Avaliação — '.$area);$msg=iflash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?>
<section class="internal-event-info evaluation-list-head"><span><?=e($test['title'])?> · <?=e(date('d/m/Y',strtotime($test['test_date'])))?></span><h2><?=e($area)?></h2><p><?=$test['status']==='ABERTO'?'Selecione um aluno para avaliar. A pontuação máxima é 100 pontos e a nota final é a média dos 10 critérios.':'Teste finalizado e relatório enviado ao Admin. As avaliações agora estão somente para consulta.'?></p><div class="evaluation-score-legend"><b>REGULAR <em>5</em></b><b>BOM <em>8</em></b><b>ÓTIMO <em>9</em></b><b>EXCELENTE <em>10</em></b></div></section>
<div class="student-evaluation-list"><?php foreach($students as $s):$d=$done[(int)$s['id']]??null;?><article><div><span><?=e($s['registration_number'])?></span><h3><?=e(evaluation_student_name($s))?></h3><p><?=e($area)?></p></div><?php if($d):?><div class="student-score-stack"><strong class="student-final-score"><?=e(evaluation_score_text((float)$d['final_score']))?></strong><small><?=e(evaluation_points_text((int)$d['total_points']))?></small></div><a class="instr-secondary" href="avaliacao_detalhe.php?id=<?=$d['id']?>">VER AVALIAÇÃO</a><?php if($test['status']==='ABERTO'):?><a class="instr-primary" href="avaliar.php?test_id=<?=$testId?>&area=<?=urlencode($area)?>&student_id=<?=$s['id']?>">REVISAR NOTA</a><?php endif;?><?php elseif($test['status']==='ABERTO'):?><a class="instr-primary" href="avaliar.php?test_id=<?=$testId?>&area=<?=urlencode($area)?>&student_id=<?=$s['id']?>">AVALIAR AGORA</a><?php else:?><span class="eval-not-done">NÃO AVALIADO</span><?php endif;?></article><?php endforeach;?><?php if(!$students):?><div class="internal-event-info">Nenhum aluno aprovado está cadastrado nesta ala.</div><?php endif;?></div>
<p><a class="instr-secondary" href="avaliacoes.php">← VOLTAR AOS MEUS TESTES</a></p>
<?php instructor_footer();?>
