<?php
require __DIR__.'/_layout.php';$u=require_instructor();$pdo=db();$id=(int)($_GET['id']??0);$st=$pdo->prepare("SELECT s.*,t.title,t.test_date,t.status test_status,e.student_name,e.preferred_name,e.registration_number,e.instrument,e.student_phone,e.guardian_phone,e.is_minor FROM evaluation_submissions s JOIN evaluation_tests t ON t.id=s.test_id JOIN enrollments e ON e.id=s.student_id WHERE s.id=? AND s.instructor_id=?");$st->execute([$id,(int)$u['id']]);$r=$st->fetch();if(!$r){http_response_code(404);exit('Avaliação não encontrada.');}$scores=evaluation_submission_scores($id);$msg=iflash();$phone=evaluation_student_phone($r);$total=(int)($r['total_points']??round((float)$r['final_score']*10));
$lines=['BAMAB — AVALIAÇÃO MUSICAL','Aluno: '.evaluation_student_name($r),'Matrícula: '.$r['registration_number'],'Ala: '.$r['area'],'Teste: '.$r['title'],'Data: '.date('d/m/Y',strtotime($r['test_date'])),''];foreach($scores as $x)$lines[]=$x['position'].'. '.$x['criterion'].' — '.$x['rating'].' ('.$x['score'].' pontos)';$lines[]='';$lines[]='PONTUAÇÃO: '.$total.'/100';$lines[]='NOTA FINAL: '.evaluation_score_text((float)$r['final_score']);$wa=$phone!==''?'https://wa.me/'.$phone.'?text='.rawurlencode(implode("\n",$lines)):'';
instructor_header('Resultado da Avaliação');?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?>
<section class="evaluation-result-card"><div><span><?=e($r['area'])?> · <?=e($r['registration_number'])?></span><h2><?=e(evaluation_student_name($r))?></h2><p><?=e($r['title'])?></p></div><div class="evaluation-result-numbers"><strong><?=e(evaluation_score_text((float)$r['final_score']))?></strong><small><?=e(evaluation_points_text($total))?></small></div></section>
<section class="panel evaluation-detail-panel"><h2>Avaliação completa do Instrutor</h2><p class="evaluation-private-note">Este detalhamento fica na sua área. Para o Admin é enviado somente o relatório final com a nota do aluno quando você encerrar o teste.</p><div class="evaluation-detail-table"><?php foreach($scores as $x):?><div><span><?=$x['position']?>.</span><p><?=e($x['criterion'])?></p><strong><?=e($x['rating'])?> · <?=$x['score']?> PONTOS</strong></div><?php endforeach;?></div><div class="evaluation-total-line"><span>TOTAL</span><strong><?=$total?> / 100 PONTOS</strong><b>NOTA <?=e(evaluation_score_text((float)$r['final_score']))?></b></div><div class="evaluation-share-actions"><?php if($wa!==''):?><a class="instr-primary" href="<?=e($wa)?>" target="_blank" rel="noopener noreferrer">ENVIAR RESULTADO PELO WHATSAPP</a><small><?=((int)$r['is_minor']===1)?'O contato utilizado é o do responsável cadastrado.':'O contato utilizado é o telefone do aluno cadastrado.'?></small><?php else:?><div class="alert error">Não há WhatsApp/telefone válido cadastrado para este aluno ou responsável.</div><?php endif;?><button type="button" class="instr-secondary" id="copyEval">COPIAR RESULTADO</button></div></section>
<p><a class="instr-secondary" href="avaliacao_alunos.php?test_id=<?=$r['test_id']?>&area=<?=urlencode($r['area'])?>">← VOLTAR À LISTA DE ALUNOS</a></p>
<script>document.getElementById('copyEval')?.addEventListener('click',async()=>{const text=<?=json_encode(implode("\n",$lines),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;try{await navigator.clipboard.writeText(text);alert('Resultado copiado.');}catch(e){prompt('Copie o resultado:',text);}});</script>
<?php instructor_footer();?>
