<?php
require __DIR__.'/_layout.php';$u=require_instructor();$pdo=db();$areas=instructor_areas((int)$u['id']);$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{csrf_check();$action=(string)($_POST['action']??'');
  if($action==='start'){$area=trim((string)($_POST['area']??''));$title=trim((string)($_POST['title']??''));$notes=trim((string)($_POST['notes']??''));$id=evaluation_create_instructor_test((int)$u['id'],$area,$title,$notes);igo('avaliacao_alunos.php?test_id='.$id.'&area='.urlencode($area),'Teste iniciado. Você pode começar a avaliar os alunos agora.');}
  if($action==='send'){$id=(int)($_POST['test_id']??0);evaluation_send_report_to_admin($id,(int)$u['id']);igo('avaliacoes.php','Teste finalizado. Somente o relatório final com as notas foi enviado ao Admin.');}
 }catch(Throwable $e){$err=$e->getMessage();}
}
$st=$pdo->prepare("SELECT t.*,(SELECT area FROM evaluation_test_areas a WHERE a.test_id=t.id ORDER BY area LIMIT 1) area,(SELECT COUNT(*) FROM evaluation_submissions s WHERE s.test_id=t.id AND s.instructor_id=? AND s.status='CONCLUIDA') done FROM evaluation_tests t WHERE t.owner_instructor_id=? ORDER BY t.id DESC");$st->execute([(int)$u['id'],(int)$u['id']]);$tests=$st->fetchAll();
instructor_header('Avaliações Musicais');$msg=iflash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<section class="instructor-welcome evaluation-welcome"><div><span>AVALIAÇÃO MUSICAL BAMAB</span><h2>Você inicia o teste quando precisar</h2><p>Escolha uma ala vinculada ao seu usuário e inicie uma avaliação a qualquer momento. Cada aluno recebe 10 pontuações: <strong>REGULAR 5</strong>, <strong>BOM 8</strong>, <strong>ÓTIMO 9</strong> ou <strong>EXCELENTE 10</strong>.</p><small>O teste fica somente na sua área enquanto estiver aberto. O Admin só recebe o relatório final depois que você mandar finalizar.</small></div></section>
<section class="panel instructor-start-evaluation"><div class="evaluation-section-head"><div><span>NOVO TESTE</span><h2>Iniciar teste agora</h2><p>Você pode iniciar um teste para qualquer uma das suas alas. O sistema carrega automaticamente os 10 critérios específicos daquela área.</p></div></div><?php if($areas):?><form method="post" class="form-stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="start"><div class="grid2"><label>Instrumento / Ala<select name="area" required><option value="">SELECIONE</option><?php foreach($areas as $area):?><option value="<?=e($area)?>"><?=e($area)?></option><?php endforeach;?></select></label><label>Nome do teste (opcional)<input name="title" placeholder="Se deixar vazio, o sistema cria o nome automaticamente"></label></div><label>Observação interna (opcional)<textarea name="notes" rows="2" placeholder="Orientação ou objetivo específico deste teste"></textarea></label><button class="instr-primary eval-start-btn">INICIAR TESTE AGORA</button></form><?php else:?><div class="alert error">Seu usuário ainda não possui uma ala vinculada. Procure o Admin Geral.</div><?php endif;?></section>
<section class="panel"><div class="evaluation-section-head"><div><span>MEUS TESTES</span><h2>Avaliações iniciadas por você</h2></div></div><div class="instructor-own-test-list"><?php foreach($tests as $t):$area=(string)$t['area'];$st2=$pdo->prepare("SELECT COUNT(*) FROM enrollments WHERE status='APROVADA' AND deleted_at IS NULL AND instrument=?");$st2->execute([$area]);$total=(int)$st2->fetchColumn();$done=(int)$t['done'];?><article class="instructor-eval-test <?=$t['status']==='ABERTO'?'is-open':'is-sent'?>"><div class="eval-card-head"><span class="eval-status <?=$t['status']==='ABERTO'?'open':'closed'?>"><?=$t['status']==='ABERTO'?'EM AVALIAÇÃO':'ENVIADO AO ADMIN'?></span><strong><?=e(date('d/m/Y',strtotime($t['test_date'])))?><?php if(!empty($t['started_at'])):?> · <?=e(date('H:i',strtotime($t['started_at'])))?><?php endif;?></strong></div><h3><?=e($t['title'])?></h3><p><strong><?=e($area)?></strong> · <?=$done?> de <?=$total?> aluno(s) avaliados</p><div class="eval-progress"><i style="width:<?=$total?min(100,round($done*100/$total)):0?>%"></i></div><div class="eval-test-actions"><a class="instr-primary" href="avaliacao_alunos.php?test_id=<?=(int)$t['id']?>&area=<?=urlencode($area)?>"><?=$t['status']==='ABERTO'?'CONTINUAR AVALIAÇÃO':'VER MINHAS AVALIAÇÕES'?></a><?php if($t['status']==='ABERTO'):?><form method="post" onsubmit="return confirm('Finalizar este teste e enviar SOMENTE o relatório final de notas ao Admin? Depois disso as notas não poderão ser alteradas.')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="send"><input type="hidden" name="test_id" value="<?=(int)$t['id']?>"><button class="eval-send-admin">FINALIZAR E ENVIAR RELATÓRIO AO ADMIN</button></form><?php else:?><span class="eval-sent-time">Enviado <?=!empty($t['submitted_to_admin_at'])?e(date('d/m/Y H:i',strtotime($t['submitted_to_admin_at']))):''?></span><?php endif;?></div></article><?php endforeach;?><?php if(!$tests):?><div class="internal-event-info"><h2>Você ainda não iniciou nenhum teste</h2><p>Use o formulário acima quando quiser começar a primeira avaliação da sua ala.</p></div><?php endif;?></div></section>
<?php instructor_footer();?>
