<?php
require __DIR__.'/_layout.php';$u=require_instructor();$areas=instructor_areas((int)$u['id']);$selected=trim((string)($_GET['area']??($areas[0]??'')));
if($selected!==''&&!in_array($selected,$areas,true)){http_response_code(403);exit('Ala não autorizada.');}
$rows=$selected!==''?instructor_frequency_for_area((int)$u['id'],$selected):[];
instructor_header('Frequência dos Alunos');?>
<section class="internal-event-info"><span>ACOMPANHAMENTO DO PROFESSOR</span><h2>Frequência dos alunos</h2><p>Mostra o histórico dos ensaios registrados para as alas sob sua responsabilidade. Presença completa exige ENTRADA + SAÍDA.</p><div class="instructor-area-shortcuts"><?php foreach($areas as $a):?><a class="<?=$a===$selected?'selected-area':''?>" href="?area=<?=urlencode($a)?>"><?=e($a)?></a><?php endforeach;?></div></section>
<?php if($selected):?><div class="report-toolbar no-print"><a class="instr-primary" target="_blank" rel="noopener noreferrer" href="frequencia_relatorio.php?area=<?=urlencode($selected)?>">IMPRIMIR RELATÓRIO A4</a><a class="instr-primary" target="_blank" rel="noopener noreferrer" href="frequencia_relatorio.php?area=<?=urlencode($selected)?>&export=xls">EXPORTAR EXCEL</a></div>
<section class="frequency-summary"><div><span>ALA</span><strong><?=e($selected)?></strong></div><div><span>ALUNOS ATIVOS</span><strong><?=count($rows)?></strong></div><div><span>ENSAIOS CONSIDERADOS</span><strong><?=$rows?(int)$rows[0]['total']:0?></strong></div></section>
<section class="frequency-list"><div class="frequency-head"><span>Aluno</span><span>Completas</span><span>Saída pendente</span><span>Ausências</span><span>Frequência</span></div><?php foreach($rows as $r):?><article><div><strong><?=e($r['preferred']?:$r['name'])?></strong><small><?=e($r['number'])?></small></div><b><?=$r['complete']?> / <?=$r['total']?></b><b><?=$r['entry_only']?></b><b><?=$r['absent']?></b><div class="frequency-meter"><span style="width:<?=max(0,min(100,(float)$r['percentage']))?>%"></span><strong><?=e(number_format((float)$r['percentage'],1,',','.'))?>%</strong></div></article><?php endforeach;?><?php if(!$rows):?><p>Nenhum aluno ativo nesta ala.</p><?php endif;?></section><?php else:?><div class="alert error">Nenhuma ala foi atribuída ao seu cadastro.</div><?php endif;?>
<?php instructor_footer();?>
