<?php
require __DIR__.'/_layout.php';$u=require_instructor();$pdo=db();$areas=instructor_areas((int)$u['id']);
// AQUI acontece a atualização automática da data: cada acesso cria/reaproveita o controle de HOJE.
$todayEvents=ensure_today_attendance_events((int)$u['id']);$today=today_bamab_date();$weekday=today_bamab_weekday();
instructor_header('Minhas Alas');$msg=iflash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?>
<section class="instructor-welcome"><div><span><?=e($u['role'])?> · <?=e(bamab_greeting())?></span><h2><?=e(instructor_display_name($u))?></h2><p><?=e(bamab_music_phrase())?></p><small>Você tem acesso somente às alas definidas pelo Admin Geral.</small></div><div class="instructor-today"><small>DATA ATUALIZADA AUTOMATICAMENTE</small><strong><?=e(bamab_weekday_label($weekday))?></strong><b><?=e(date('d/m/Y'))?></b></div></section>
<section class="professor-simple-actions"><a class="prof-action main" href="#controles-hoje"><strong>ABRIR CONTROLE</strong><span>Entrada e saída por QR</span></a><a class="prof-action" href="avaliacoes.php"><strong>AVALIAÇÕES MUSICAIS</strong><span>Inicie seus testes a qualquer momento e avalie 10 critérios por aluno</span></a><a class="prof-action" href="meu_qr.php"><strong>MINHA CREDENCIAL QR</strong><span>QR pessoal para registrar sua entrada e saída nas atividades BAMAB</span></a><a class="prof-action" href="frequencia.php"><strong>FREQUÊNCIA DOS ALUNOS</strong><span>Percentual por aluno e por ala</span></a><a class="prof-action" href="relatorios.php"><strong>RELATÓRIOS</strong><span>Presentes e ausentes dos ensaios</span></a></section>
<div id="controles-hoje"></div>
<?php if($todayEvents):?><section class="internal-event-info"><span>PROGRAMAÇÃO DE HOJE</span><h2><?=e(bamab_weekday_label($weekday))?> · <?=e(date('d/m/Y'))?></h2><p>Escolha abaixo a sua ala e abra o controle de entrada/saída.</p></section><section class="instructor-area-cards"><?php foreach($todayEvents as $event):$eventAreas=attendance_event_areas((int)$event['id']);foreach(array_values(array_intersect($areas,$eventAreas)) as $area):$c=attendance_area_control((int)$event['id'],$area);?><article><span><?=e($event['event_type'])?> · <?=e($area)?></span><h3><?=e($event['title'])?></h3><p><?= $event['start_time']?e($event['start_time']):'Horário livre'?><?= $event['end_time']?' às '.e($event['end_time']):''?></p><strong><?=e(attendance_phase_label($c['phase']))?></strong><a class="instr-primary" href="presenca.php?event_id=<?=$event['id']?>&area=<?=urlencode($area)?>">ABRIR CONTROLE DA ALA</a></article><?php endforeach;endforeach;?></section><?php else:?><section class="internal-event-info"><span>HOJE: <?=e(bamab_weekday_label($weekday))?></span><h2>Nenhum ensaio/reunião programado para suas alas</h2><p>A data foi atualizada para <?=e(date('d/m/Y'))?>, mas não existe programação ativa neste dia da semana para as alas sob sua responsabilidade.</p></section><?php endif;?>
<?php if(!$areas):?><div class="alert error">Nenhuma ala foi atribuída ao seu cadastro. Procure o Admin Geral.</div><?php endif;?>
<?php instructor_footer();?>
