<?php
require __DIR__.'/_layout.php';$u=require_instructor();$pdo=db();$err='';$myAreas=instructor_areas((int)$u['id']);$eventId=(int)($_GET['event_id']??$_POST['event_id']??0);$area=trim((string)($_GET['area']??$_POST['area']??''));
// Garante que a programação do dia atual já esteja materializada antes da leitura.
ensure_today_attendance_events((int)$u['id']);
$st=$pdo->prepare("SELECT * FROM attendance_events WHERE id=? AND active=1 AND event_date=? AND control_mode IN ('ALA_DUAL','ALA_DUAL_WEEKDAY')");$st->execute([$eventId,today_bamab_date()]);$event=$st->fetch();if(!$event&&$eventId){$err='Este ensaio/reunião não está ativo.';}$authorized=$event&&in_array($area,$myAreas,true)&&attendance_event_has_area($eventId,$area);if($event&&$area!==''&&!$authorized)$err='Você não possui autorização para controlar esta ala.';
function instructor_student_check(array $identity,string $area): array {if(($identity['type']??'')!=='ALUNO')return [false,'Este leitor por ala aceita somente QR de alunos/integrantes.'];$st=db()->prepare("SELECT e.instrument,e.status,c.status card_status,c.valid_until FROM enrollments e LEFT JOIN student_cards c ON c.enrollment_id=e.id WHERE e.id=? AND e.deleted_at IS NULL");$st->execute([$identity['id']]);$r=$st->fetch();if(!$r||$r['status']!=='APROVADA')return [false,'Aluno não está com matrícula aprovada.'];if($r['instrument']!==$area)return [false,'Este aluno pertence à ala '.$r['instrument'].'. O leitor atual é '.$area.'.'];if(($r['card_status']??'')!=='ATIVA')return [false,'Carteirinha não está ativa.'];if(($r['valid_until']??'0000-00-00')<date('Y-m-d'))return [false,'Carteirinha vencida.'];return [true,''];}
if($_SERVER['REQUEST_METHOD']==='POST'){$ajax=($_POST['ajax']??'')==='1';if($ajax)header('Content-Type:application/json; charset=UTF-8');try{csrf_check();$action=$_POST['action']??'';if(!$authorized)throw new RuntimeException('Acesso à ala não autorizado.');$control=attendance_area_control($eventId,$area);
 if(in_array($action,['open_entry','close_entry','open_exit','close_exit'],true)){
  $phase=$control['phase'];$now=now_iso();
  if($action==='open_entry'){if($phase!=='FECHADO')throw new RuntimeException('A entrada já foi iniciada ou encerrada.');attendance_freeze_roster($event);$pdo->prepare("UPDATE attendance_area_controls SET phase='ENTRADA',entry_opened_at=?,last_instructor_id=?,updated_at=? WHERE event_id=? AND area=?")->execute([$now,(int)$u['id'],$now,$eventId,$area]);$m='Leitura de ENTRADA aberta.';}
  elseif($action==='close_entry'){if($phase!=='ENTRADA')throw new RuntimeException('A entrada não está aberta.');$pdo->prepare("UPDATE attendance_area_controls SET phase='INTERVALO',entry_closed_at=?,last_instructor_id=?,updated_at=? WHERE event_id=? AND area=?")->execute([$now,(int)$u['id'],$now,$eventId,$area]);$m='Entrada encerrada. Abra a SAÍDA somente no final.';}
  elseif($action==='open_exit'){if($phase!=='INTERVALO')throw new RuntimeException('Encerre a entrada antes de abrir a saída.');$pdo->prepare("UPDATE attendance_area_controls SET phase='SAIDA',exit_opened_at=?,last_instructor_id=?,updated_at=? WHERE event_id=? AND area=?")->execute([$now,(int)$u['id'],$now,$eventId,$area]);$m='Leitura de SAÍDA aberta.';}
  else{if($phase!=='SAIDA')throw new RuntimeException('A saída não está aberta.');$pdo->prepare("UPDATE attendance_area_controls SET phase='CONCLUIDO',exit_closed_at=?,last_instructor_id=?,updated_at=? WHERE event_id=? AND area=?")->execute([$now,(int)$u['id'],$now,$eventId,$area]);$_SESSION['instructor_flash']='Controle concluído. Lista de presentes e ausentes gerada automaticamente.';header('Location: relatorio.php?event_id='.$eventId.'&area='.urlencode($area));exit;}
  igo('presenca.php?event_id='.$eventId.'&area='.urlencode($area),$m);
 }
 if($action==='scan'){$control=attendance_area_control($eventId,$area);$phase=$control['phase'];if(!in_array($phase,['ENTRADA','SAIDA'],true))throw new RuntimeException('A leitura não está aberta. Use os botões de ENTRADA/SAÍDA.');$checkType=$phase==='ENTRADA'?'ENTRADA':'SAIDA';$payload=trim((string)($_POST['payload']??''));$number=trim((string)($_POST['number']??''));$identity=$payload!==''?attendance_identity_from_payload($payload):null;if(!$identity&&$number!=='')$identity=attendance_identity_from_number($number);if(!$identity)throw new RuntimeException('QR ou matrícula não reconhecido.');[$ok,$why]=instructor_student_check($identity,$area);if(!$ok)throw new RuntimeException($why);if($checkType==='SAIDA'){$st=$pdo->prepare("SELECT scanned_at FROM attendance_checks WHERE event_id=? AND person_type='ALUNO' AND person_id=? AND check_type='ENTRADA'");$st->execute([$eventId,$identity['id']]);if(!$st->fetchColumn())throw new RuntimeException('Não há ENTRADA registrada para este aluno.');}$st=$pdo->prepare("SELECT scanned_at FROM attendance_checks WHERE event_id=? AND person_type='ALUNO' AND person_id=? AND check_type=?");$st->execute([$eventId,$identity['id'],$checkType]);$existing=$st->fetchColumn();if($existing){$response=['ok'=>true,'duplicate'=>true,'message'=>$checkType.' já registrada às '.date('H:i',strtotime((string)$existing)).'.','person'=>$identity,'check_type'=>$checkType];}else{$pdo->prepare("INSERT INTO attendance_checks(event_id,person_type,person_id,area,check_type,scanned_at,scan_method,instructor_id) VALUES(?,'ALUNO',?,?,?,?,?,?)")->execute([$eventId,$identity['id'],$area,$checkType,now_iso(),$payload!==''?'QR':'MANUAL',(int)$u['id']]);$response=['ok'=>true,'duplicate'=>false,'message'=>$checkType.' REGISTRADA','person'=>$identity,'check_type'=>$checkType,'time'=>date('H:i')];}if($ajax){echo json_encode($response,JSON_UNESCAPED_UNICODE);exit;}}
 }catch(Throwable $e){if($ajax){http_response_code(400);echo json_encode(['ok'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);exit;}$err=$e->getMessage();}}
$control=$authorized?attendance_area_control($eventId,$area):null;$entryCount=$exitCount=0;$recent=[];if($authorized){$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_checks WHERE event_id=? AND area=? AND person_type='ALUNO' AND check_type='ENTRADA'");$st->execute([$eventId,$area]);$entryCount=(int)$st->fetchColumn();$st=$pdo->prepare("SELECT COUNT(*) FROM attendance_checks WHERE event_id=? AND area=? AND person_type='ALUNO' AND check_type='SAIDA'");$st->execute([$eventId,$area]);$exitCount=(int)$st->fetchColumn();$st=$pdo->prepare("SELECT ac.*,e.student_name,e.preferred_name,e.registration_number FROM attendance_checks ac JOIN enrollments e ON e.id=ac.person_id WHERE ac.event_id=? AND ac.area=? AND ac.person_type='ALUNO' ORDER BY ac.scanned_at DESC LIMIT 20");$st->execute([$eventId,$area]);$recent=$st->fetchAll();}
instructor_header('Presença QR por Ala');$msg=iflash();?>
<?php if($msg):?><div class="alert ok"><?=e($msg)?></div><?php endif;?><?php if($err):?><div class="alert error"><?=e($err)?></div><?php endif;?>
<?php if(!$authorized):?><section class="internal-event-info"><h2>Escolha uma ala autorizada</h2><div class="instructor-area-shortcuts"><?php foreach($myAreas as $a):?><?php if($event&&attendance_event_has_area((int)$event['id'],$a)):?><a href="?event_id=<?=$event['id']?>&area=<?=urlencode($a)?>"><?=e($a)?></a><?php endif;?><?php endforeach;?></div><a class="instr-secondary" href="index.php">VOLTAR</a></section><?php else:?>
<section class="area-live-header"><div><span><?=e($event['event_type'])?> · <?=e(date('d/m/Y',strtotime($event['event_date'])))?></span><h2><?=e($area)?></h2><p><?=e($event['title'])?></p></div><div class="area-live-numbers"><b>ENTRADA <?=$entryCount?></b><b>SAÍDA <?=$exitCount?></b></div></section>
<section class="phase-controller"><div class="phase-current"><span>ETAPA ATUAL</span><strong><?=e(attendance_phase_label($control['phase']))?></strong></div><div class="phase-buttons"><?php if($control['phase']==='FECHADO'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="open_entry"><input type="hidden" name="event_id" value="<?=$eventId?>"><input type="hidden" name="area" value="<?=e($area)?>"><button class="phase-entry">ABRIR ENTRADA</button></form><?php elseif($control['phase']==='ENTRADA'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close_entry"><input type="hidden" name="event_id" value="<?=$eventId?>"><input type="hidden" name="area" value="<?=e($area)?>"><button class="phase-stop">ENCERRAR ENTRADA</button></form><?php elseif($control['phase']==='INTERVALO'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="open_exit"><input type="hidden" name="event_id" value="<?=$eventId?>"><input type="hidden" name="area" value="<?=e($area)?>"><button class="phase-exit">ABRIR SAÍDA NO FINAL</button></form><?php elseif($control['phase']==='SAIDA'):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="close_exit"><input type="hidden" name="event_id" value="<?=$eventId?>"><input type="hidden" name="area" value="<?=e($area)?>"><button class="phase-stop">CONCLUIR ALA</button></form><?php endif;?></div></section>
<?php if(in_array($control['phase'],['ENTRADA','SAIDA'],true)):?><section class="instructor-scanner"><div class="scanner-mode <?=$control['phase']==='ENTRADA'?'entry-mode':'exit-mode'?>"><?=$control['phase']==='ENTRADA'?'LEITURA DE ENTRADA':'LEITURA DE SAÍDA'?></div><div class="scanner-grid"><div class="camera-box"><video id="qrVideo" playsinline muted></video><div id="cameraMessage">Clique em ABRIR CÂMERA e autorize o acesso.</div></div><div class="scan-result" id="scanResult"><strong>AGUARDANDO QR</strong><span>Somente alunos da ala <?=e($area)?> serão aceitos.</span></div></div><div class="scanner-actions"><button type="button" class="primary" id="startCamera">ABRIR CÂMERA</button><button type="button" class="small-button" id="stopCamera">PARAR</button></div><form id="manualPresence" class="manual-presence"><label>Matrícula manual<input id="manualNumber" placeholder="BAMAB-2026-000001"></label><button type="submit" class="small-button">REGISTRAR</button></form></section><script>
(()=>{const csrf=<?=json_encode(csrf_token())?>,eventId=<?=$eventId?>,area=<?=json_encode($area)?>,video=document.getElementById('qrVideo'),result=document.getElementById('scanResult'),msg=document.getElementById('cameraMessage');let stream=null,detector=null,running=false,last='',lastAt=0;function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function send(data){const body=new URLSearchParams({csrf,action:'scan',ajax:'1',event_id:String(eventId),area,...data});try{const r=await fetch('presenca.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.message||'Falha');const n=j.person.preferred||j.person.name;result.className='scan-result success';result.innerHTML='<strong>'+esc(j.message)+'</strong><b>'+esc(n)+'</b><span>'+esc(j.person.number+' · '+area)+'</span>';if(navigator.vibrate)navigator.vibrate(j.duplicate?[80]:[100,60,100]);}catch(e){result.className='scan-result failure';result.innerHTML='<strong>NÃO REGISTRADO</strong><span>'+esc(e.message)+'</span>';if(navigator.vibrate)navigator.vibrate([250]);}}async function loop(){if(!running||!detector)return;try{const codes=await detector.detect(video);if(codes.length){const raw=codes[0].rawValue||'';const now=Date.now();if(raw&&(raw!==last||now-lastAt>3000)){last=raw;lastAt=now;await send({payload:raw});}}}catch(e){}setTimeout(loop,300)}document.getElementById('startCamera').onclick=async()=>{try{if(!('BarcodeDetector'in window))throw new Error('Leitura automática não disponível. Use Chrome/Edge atualizado ou matrícula manual.');detector=new BarcodeDetector({formats:['qr_code']});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=stream;await video.play();running=true;msg.textContent='Câmera ativa — aproxime o QR.';loop();}catch(e){msg.textContent=e.message}};document.getElementById('stopCamera').onclick=()=>{running=false;if(stream)stream.getTracks().forEach(t=>t.stop());video.srcObject=null;msg.textContent='Câmera parada.'};document.getElementById('manualPresence').onsubmit=async e=>{e.preventDefault();const number=document.getElementById('manualNumber').value.trim();if(number)await send({number})};})();</script><?php endif;?>
<section class="recent-checks"><h3>Últimas leituras — <?=e($area)?></h3><?php foreach($recent as $r):?><div><span class="<?=$r['check_type']==='ENTRADA'?'check-entry':'check-exit'?>"><?=e($r['check_type'])?></span><strong><?=e($r['preferred_name']?:$r['student_name'])?></strong><small><?=e($r['registration_number'])?> · <?=e(date('H:i:s',strtotime($r['scanned_at'])))?></small></div><?php endforeach;?><?php if(!$recent):?><p>Nenhuma leitura nesta ala ainda.</p><?php endif;?></section>
<?php endif;?><?php instructor_footer();?>
