<?php
require __DIR__.'/../config.php';
require __DIR__.'/../report_helpers.php';
$u=require_instructor();$pdo=db();$eventId=(int)($_GET['event_id']??0);$area=trim((string)($_GET['area']??''));
if(!instructor_has_area((int)$u['id'],$area)){http_response_code(403);exit('Ala não autorizada.');}
$st=$pdo->prepare("SELECT * FROM attendance_events WHERE id=?");$st->execute([$eventId]);$event=$st->fetch();if(!$event||!attendance_event_has_area($eventId,$area)){http_response_code(404);exit('Relatório não encontrado.');}
$students=attendance_expected_students_for_area($event,$area);
$st=$pdo->prepare("SELECT person_id,check_type,scanned_at FROM attendance_checks WHERE event_id=? AND area=? AND person_type='ALUNO'");$st->execute([$eventId,$area]);$checks=[];foreach($st->fetchAll() as $c)$checks[$c['person_id']][$c['check_type']]=$c['scanned_at'];
$present=[];$absent=[];$pending=[];foreach($students as $s){$en=$checks[$s['id']]['ENTRADA']??null;$ex=$checks[$s['id']]['SAIDA']??null;$s['entry']=$en;$s['exit']=$ex;if($en&&$ex)$present[]=$s;elseif($en)$pending[]=$s;else$absent[]=$s;}
$export=(string)($_GET['export']??'');
if($export==='xls'){
    bamab_report_excel_headers('relatorio_ensaio_'.preg_replace('/[^A-Za-z0-9_-]+/','_', $area).'_'.date('Y-m-d').'.xls');
    $logo=bamab_report_logo_data_uri();
    echo '<!doctype html><html><head><meta charset="utf-8">'.bamab_report_excel_style_block().'</head><body><div class="sheet-wrap">';
    echo '<div class="sheet-head">'.($logo?'<img src="'.$logo.'" alt="Brasão">':'').'<div><h1>RELATÓRIO DO ENSAIO</h1><p>'.e(report_location_line()).' · '.e($event['title']).' · '.e($area).' · '.e(date('d/m/Y',strtotime($event['event_date']))).'</p></div></div>';
    echo '<div class="sheet-meta"><div><strong>'.count($present).'</strong><small>Presentes</small></div><div><strong>'.count($pending).'</strong><small>Saída pendente</small></div><div><strong>'.count($absent).'</strong><small>Não foram ao ensaio</small></div></div>';
    $sections=[['Presentes',$present,['Nome','Matrícula','Entrada','Saída']],['Entrada registrada / saída pendente',$pending,['Nome','Matrícula','Entrada']],['Não foram ao ensaio',$absent,['Nome','Matrícula']]];
    foreach($sections as [$title,$list,$cols]){echo '<div class="sheet-block"><h2>'.e($title).'</h2><table class="sheet-table"><thead><tr>';foreach($cols as $c)echo '<th>'.e($c).'</th>';echo '</tr></thead><tbody>';if($list){foreach($list as $s){echo '<tr><td>'.e($s['preferred_name']?:$s['student_name']).'</td><td>'.e($s['registration_number']).'</td>';if(count($cols)>=3)echo '<td>'.(isset($s['entry'])&&$s['entry']?e(date('H:i',strtotime($s['entry']))):'—').'</td>';if(count($cols)>=4)echo '<td>'.(isset($s['exit'])&&$s['exit']?e(date('H:i',strtotime($s['exit']))):'—').'</td>';echo '</tr>';}} else echo '<tr><td colspan="'.count($cols).'">Nenhum registro neste grupo.</td></tr>';echo '</tbody></table></div>';}
    echo '<table class="sheet-sign"><tr><td><div class="line"></div><strong>COORDENADOR GERAL</strong></td><td><div class="line"></div><strong>INSTRUTOR RESPONSÁVEL</strong><br>'.e(instructor_display_name($u)).'</td><td><div class="line"></div><strong>SECRETÁRIO(A)</strong></td></tr></table><div class="footer-note">Relatório gerado em '.date('d/m/Y H:i').'.</div></div></body></html>';
    exit;
}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Relatório do Ensaio</title><link rel="stylesheet" href="../assets/report_a4.css"><?=bamab_report_style_block('../')?></head><body><div class="a4-toolbar no-print"><a href="relatorios.php">← VOLTAR</a><button onclick="window.print()">IMPRIMIR / PDF A4</button><a href="?event_id=<?=$eventId?>&area=<?=urlencode($area)?>&export=xls">EXCEL</a></div><main class="a4-document"><header class="a4-header"><img src="<?=e(bamab_report_logo_web('../'))?>" alt="Brasão"><div class="a4-location"><?=e(report_location_line())?></div></header><section class="a4-title"><h1>RELATÓRIO DO ENSAIO</h1><p><?=e($event['title'])?> · <?=e($area)?> · <?=e(date('d/m/Y',strtotime($event['event_date'])))?></p></section><div class="a4-counts"><div><strong><?=count($present)?></strong><span>Presentes</span></div><div><strong><?=count($pending)?></strong><span>Saída pendente</span></div><div><strong><?=count($absent)?></strong><span>Não foram ao ensaio</span></div></div>
<section class="a4-section"><h2>Presentes</h2><table class="a4-table"><thead><tr><th>Nome</th><th>Matrícula</th><th>Entrada</th><th>Saída</th></tr></thead><tbody><?php foreach($present as $s):?><tr><td><?=e($s['preferred_name']?:$s['student_name'])?></td><td><?=e($s['registration_number'])?></td><td><?=e(date('H:i',strtotime($s['entry'])))?></td><td><?=e(date('H:i',strtotime($s['exit'])))?></td></tr><?php endforeach;?><?php if(!$present):?><tr><td colspan="4">Nenhum aluno com presença completa.</td></tr><?php endif;?></tbody></table></section>
<?php if($pending):?><section class="a4-section"><h2>Entrada registrada / saída pendente</h2><table class="a4-table"><thead><tr><th>Nome</th><th>Matrícula</th><th>Entrada</th></tr></thead><tbody><?php foreach($pending as $s):?><tr><td><?=e($s['preferred_name']?:$s['student_name'])?></td><td><?=e($s['registration_number'])?></td><td><?=e(date('H:i',strtotime($s['entry'])))?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
<section class="a4-section"><h2>Não foram ao ensaio</h2><table class="a4-table"><thead><tr><th>Nome</th><th>Matrícula</th></tr></thead><tbody><?php foreach($absent as $s):?><tr><td><?=e($s['preferred_name']?:$s['student_name'])?></td><td><?=e($s['registration_number'])?></td></tr><?php endforeach;?><?php if(!$absent):?><tr><td colspan="2">Nenhuma ausência.</td></tr><?php endif;?></tbody></table></section>
<section class="a4-signatures"><div class="a4-signature"><div class="line"></div><strong>COORDENADOR GERAL</strong></div><div class="a4-signature"><div class="line"></div><strong>INSTRUTOR RESPONSÁVEL</strong><span><?=e(instructor_display_name($u))?></span></div><div class="a4-signature"><div class="line"></div><strong>SECRETÁRIO(A)</strong></div></section><footer class="a4-footer">Relatório gerado em <?=date('d/m/Y H:i')?>.</footer></main></body></html>
